import type { LeiterFrage } from '../../core/leiter';

/**
 * Kultur, Sport, Essen, Mythologie und Alltag für die oberen Stufen der Gewinnleiter — reine Daten.
 * Je 17 Fragen der Schwere 3, 4 und 5. Die leichten Grundfragen stehen in `fragen.ts`; was dort schon
 * gefragt wird, kommt hier nicht noch einmal vor.
 */
export const FRAGEN_SCHWER_KULTUR: readonly LeiterFrage[] = [
  // Schwere 3 — Klasse 7 bis 9, solides Allgemeinwissen
  { kategorie: 'Kunst', frage: 'Wer malte das berühmte Bild „Der Schrei"?', antworten: ['Edvard Munch', 'Gustav Klimt', 'Egon Schiele', 'Ernst Ludwig Kirchner'], richtig: 0, erklaerung: 'Der Norweger Edvard Munch schuf das Motiv 1893 und stellte es danach in mehreren Fassungen dar, als Gemälde, Pastell und Druck.', schwere: 3 },
  { kategorie: 'Kunst', frage: 'Wer malte die Decke der Sixtinischen Kapelle im Vatikan?', antworten: ['Raffael', 'Michelangelo', 'Leonardo da Vinci', 'Sandro Botticelli'], richtig: 1, erklaerung: 'Michelangelo bemalte die Decke von 1508 bis 1512. Das bekannteste Bild daraus ist die Erschaffung Adams.', schwere: 3 },
  { kategorie: 'Musik', frage: 'Aus welcher englischen Stadt stammt die Band The Beatles?', antworten: ['Manchester', 'London', 'Liverpool', 'Birmingham'], richtig: 2, erklaerung: 'Alle vier Bandmitglieder stammen aus Liverpool. Bevor sie weltberühmt wurden, spielten sie oft im Cavern Club in Liverpool und in Clubs in Hamburg.', schwere: 3 },
  { kategorie: 'Musik', frage: 'In welcher Stadt wurde Wolfgang Amadeus Mozart geboren?', antworten: ['Wien', 'Linz', 'Innsbruck', 'Salzburg'], richtig: 3, erklaerung: 'Mozart kam 1756 in Salzburg zur Welt. Sein Geburtshaus in der Getreidegasse ist heute ein Museum.', schwere: 3 },
  { kategorie: 'Musik', frage: 'Welcher Komponist schrieb „Die vier Jahreszeiten"?', antworten: ['Antonio Vivaldi', 'Johann Sebastian Bach', 'Georg Friedrich Händel', 'Giuseppe Verdi'], richtig: 0, erklaerung: 'Die vier Violinkonzerte des Italieners Vivaldi stellen Frühling, Sommer, Herbst und Winter in Musik dar, etwa mit Vogelgezwitscher oder einem Gewitter.', schwere: 3 },
  { kategorie: 'Literatur', frage: 'Wer schrieb das Kinderbuch „Emil und die Detektive"?', antworten: ['Otfried Preußler', 'Erich Kästner', 'Michael Ende', 'Cornelia Funke'], richtig: 1, erklaerung: 'Das Buch erschien 1929. Emil jagt darin mit einer Bande Berliner Kinder den Dieb, der ihm sein Geld gestohlen hat.', schwere: 3 },
  { kategorie: 'Literatur', frage: 'Welcher Schriftsteller erfand den Detektiv Sherlock Holmes?', antworten: ['Agatha Christie', 'Edgar Allan Poe', 'Arthur Conan Doyle', 'Charles Dickens'], richtig: 2, erklaerung: 'Sherlock Holmes wohnt in der Baker Street 221b in London und löst seine Fälle zusammen mit seinem Freund Dr. Watson.', schwere: 3 },
  { kategorie: 'Literatur', frage: 'Wie heißt der Gefährte, den Robinson Crusoe auf seiner Insel trifft?', antworten: ['Sonntag', 'Montag', 'Samstag', 'Freitag'], richtig: 3, erklaerung: 'Robinson benennt ihn nach dem Wochentag, an dem er ihn rettet. Daniel Defoes Roman erschien 1719.', schwere: 3 },
  { kategorie: 'Sport', frage: 'Wie lang ist die Strecke eines Marathonlaufs?', antworten: ['42,195 km', '40,000 km', '41,500 km', '45,000 km'], richtig: 0, erklaerung: 'Diese genaue Länge stammt von den Olympischen Spielen 1908 in London und wurde 1921 als Standard festgelegt.', schwere: 3 },
  { kategorie: 'Sport', frage: 'Welche Wintersportart verbindet Skilanglauf mit Schießen?', antworten: ['Nordische Kombination', 'Biathlon', 'Skeleton', 'Riesenslalom'], richtig: 1, erklaerung: 'Bei der Nordischen Kombination werden dagegen Skispringen und Skilanglauf verbunden.', schwere: 3 },
  { kategorie: 'Essen', frage: 'Aus welchen Hülsenfrüchten wird Hummus hauptsächlich gemacht?', antworten: ['Linsen', 'Weiße Bohnen', 'Kichererbsen', 'Erbsen'], richtig: 2, erklaerung: 'Die pürierten Kichererbsen werden meist mit Sesammus (Tahini), Zitronensaft und Knoblauch abgeschmeckt.', schwere: 3 },
  { kategorie: 'Essen', frage: 'Aus welchem Land stammt das Reisgericht Paella?', antworten: ['Italien', 'Portugal', 'Mexiko', 'Spanien'], richtig: 3, erklaerung: 'Die Paella stammt aus der Region Valencia. Ihr Name bezeichnet eigentlich die flache Pfanne, in der sie gekocht wird.', schwere: 3 },
  { kategorie: 'Essen', frage: 'Welche Frucht ist die Hauptzutat von Guacamole?', antworten: ['Avocado', 'Mango', 'Papaya', 'Kiwi'], richtig: 0, erklaerung: 'Guacamole stammt aus Mexiko. Das zerdrückte Fruchtfleisch wird meist mit Limettensaft, Salz und Zwiebeln gewürzt.', schwere: 3 },
  { kategorie: 'Mythologie', frage: 'Wer flog in der griechischen Sage mit Flügeln aus Federn und Wachs zu nah an die Sonne?', antworten: ['Daidalos', 'Ikarus', 'Perseus', 'Theseus'], richtig: 1, erklaerung: 'Sein Vater Daidalos baute die Flügel, damit beide von der Insel Kreta fliehen konnten. Als das Wachs schmolz, fiel Ikarus ins Meer.', schwere: 3 },
  { kategorie: 'Mythologie', frage: 'Welches Wesen der griechischen Sage verwandelte jeden in Stein, der es ansah?', antworten: ['Sphinx', 'Hydra', 'Medusa', 'Chimäre'], richtig: 2, erklaerung: 'Medusa hatte Schlangen statt Haaren. Perseus besiegte sie, weil er sie nur als Spiegelbild in seinem blanken Schild ansah.', schwere: 3 },
  { kategorie: 'Alltag', frage: 'Welche Form hat ein Stoppschild?', antworten: ['Sechseck', 'Dreieck', 'Kreis', 'Achteck'], richtig: 3, erklaerung: 'Als einziges Verkehrszeichen ist es achteckig. So erkennt man es auch dann, wenn es verschneit oder verschmutzt ist.', schwere: 3 },
  { kategorie: 'Alltag', frage: 'Was misst ein Barometer?', antworten: ['Luftdruck', 'Temperatur', 'Luftfeuchtigkeit', 'Windstärke'], richtig: 0, erklaerung: 'Sinkender Luftdruck kündigt oft schlechteres Wetter an, steigender eher schönes.', schwere: 3 },

  // Schwere 4 — Allgemeinbildung eines Erwachsenen
  { kategorie: 'Kunst', frage: 'Wie nennt man ein Wandgemälde, das auf frischen, noch feuchten Putz gemalt wird?', antworten: ['Mosaik', 'Fresko', 'Aquarell', 'Gouache'], richtig: 1, erklaerung: 'Der Name kommt vom italienischen „fresco" für frisch. Die Farbe verbindet sich beim Trocknen fest mit dem Putz.', schwere: 4 },
  { kategorie: 'Kunst', frage: 'Welcher Wiener Maler schuf das goldglänzende Gemälde „Der Kuss"?', antworten: ['Egon Schiele', 'Oskar Kokoschka', 'Gustav Klimt', 'Koloman Moser'], richtig: 2, erklaerung: 'Klimt verwendete für das Bild echtes Blattgold. Es hängt heute im Belvedere in Wien.', schwere: 4 },
  { kategorie: 'Kunst', frage: 'Von welchem Künstler stammt das berühmte Aquarell „Feldhase" aus dem Jahr 1502?', antworten: ['Lucas Cranach', 'Hans Holbein', 'Matthias Grünewald', 'Albrecht Dürer'], richtig: 3, erklaerung: 'Dürer malte den Hasen so genau, dass man fast jedes einzelne Haar erkennt. Das Original liegt in der Albertina in Wien.', schwere: 4 },
  { kategorie: 'Musik', frage: 'Wer komponierte die Melodie der deutschen Nationalhymne?', antworten: ['Joseph Haydn', 'Ludwig van Beethoven', 'Franz Schubert', 'Wolfgang Amadeus Mozart'], richtig: 0, erklaerung: 'Haydn schrieb die Melodie 1797 für ein Lied auf den österreichischen Kaiser. Den Text des „Lieds der Deutschen" dichtete später Hoffmann von Fallersleben.', schwere: 4 },
  { kategorie: 'Musik', frage: 'Welches dieser Instrumente zählt zu den Holzblasinstrumenten, obwohl es heute meist aus Metall gebaut wird?', antworten: ['Trompete', 'Querflöte', 'Posaune', 'Tuba'], richtig: 1, erklaerung: 'Entscheidend ist die Art, wie der Ton entsteht, nicht das Material. Früher wurden Querflöten tatsächlich aus Holz gebaut.', schwere: 4 },
  { kategorie: 'Literatur', frage: 'Wer schrieb das Drama „Wilhelm Tell"?', antworten: ['Johann Wolfgang von Goethe', 'Gotthold Ephraim Lessing', 'Friedrich Schiller', 'Heinrich von Kleist'], richtig: 2, erklaerung: 'Das Drama wurde 1804 in Weimar uraufgeführt. Berühmt ist die Szene, in der Tell einen Apfel vom Kopf seines Sohnes schießen muss.', schwere: 4 },
  { kategorie: 'Literatur', frage: 'Wer schrieb den Abenteuerroman „Die Schatzinsel"?', antworten: ['Mark Twain', 'Jules Verne', 'Daniel Defoe', 'Robert Louis Stevenson'], richtig: 3, erklaerung: 'Der Schotte Stevenson erzählt darin von dem Jungen Jim Hawkins und dem einbeinigen Piraten Long John Silver.', schwere: 4 },
  { kategorie: 'Literatur', frage: 'Wie heißt der treue Knappe des Ritters Don Quijote?', antworten: ['Sancho Panza', 'Rosinante', 'Dulcinea', 'Lazarillo'], richtig: 0, erklaerung: 'Im Roman von Miguel de Cervantes reitet Sancho Panza auf einem Esel neben Don Quijote her, der Windmühlen für Riesen hält.', schwere: 4 },
  { kategorie: 'Sport', frage: 'In welcher Stadt fanden 1896 die ersten Olympischen Spiele der Neuzeit statt?', antworten: ['Paris', 'Athen', 'London', 'Olympia'], richtig: 1, erklaerung: 'Angeregt hatte die Wiederbelebung der antiken Spiele der Franzose Pierre de Coubertin. Vier Jahre später war Paris Gastgeber.', schwere: 4 },
  { kategorie: 'Sport', frage: 'Wie hoch hängt der Ring eines Basketballkorbs über dem Boden?', antworten: ['2,75 m', '2,90 m', '3,05 m', '3,25 m'], richtig: 2, erklaerung: 'Das sind genau zehn Fuß. Diese Höhe stammt noch aus der Erfindungszeit des Spiels.', schwere: 4 },
  { kategorie: 'Sport', frage: 'Wie nennt man beim Tennis den Spielstand 40:40?', antworten: ['Vorteil', 'Satzball', 'Tiebreak', 'Einstand'], richtig: 3, erklaerung: 'Wer danach den nächsten Punkt holt, hat „Vorteil". Gewinnt er auch den folgenden Punkt, gehört ihm das Spiel.', schwere: 4 },
  { kategorie: 'Essen', frage: 'Aus welchem Teil der Pflanze wird das Gewürz Zimt gewonnen?', antworten: ['Rinde', 'Samen', 'Wurzel', 'Blüte'], richtig: 0, erklaerung: 'Die Innenrinde des Zimtbaums rollt sich beim Trocknen zu den typischen Zimtstangen ein.', schwere: 4 },
  { kategorie: 'Essen', frage: 'Welches Algenblatt wird häufig um Sushi-Rollen gewickelt?', antworten: ['Wasabi', 'Nori', 'Miso', 'Tempura'], richtig: 1, erklaerung: 'Nori besteht aus getrockneten Rotalgen, die zu dünnen Blättern gepresst werden.', schwere: 4 },
  { kategorie: 'Mythologie', frage: 'Wie lautet der römische Name des griechischen Göttervaters Zeus?', antworten: ['Mars', 'Merkur', 'Jupiter', 'Neptun'], richtig: 2, erklaerung: 'Die Römer übernahmen viele griechische Götter unter eigenem Namen: Aus Poseidon wurde Neptun, aus Ares wurde Mars.', schwere: 4 },
  { kategorie: 'Mythologie', frage: 'Welches Tier gilt als Symbol der griechischen Göttin Athene?', antworten: ['Adler', 'Pfau', 'Taube', 'Eule'], richtig: 3, erklaerung: 'Athene war die Göttin der Weisheit. Deshalb gilt die Eule bis heute als Sinnbild für Klugheit.', schwere: 4 },
  { kategorie: 'Alltag', frage: 'Mit wie vielen Karten wird Skat gespielt?', antworten: ['32', '24', '36', '52'], richtig: 0, erklaerung: 'Beim Skat spielen drei Personen mit je zehn Karten. Die beiden übrigen Karten liegen verdeckt als „Skat" in der Mitte.', schwere: 4 },
  { kategorie: 'Alltag', frage: 'Wie viele Zentimeter misst ein Zoll?', antworten: ['1,85 cm', '2,54 cm', '3,00 cm', '3,48 cm'], richtig: 1, erklaerung: 'Auch die Bildschirmgröße von Fernsehern und Handys wird in Zoll angegeben, gemessen über die Diagonale.', schwere: 4 },

  // Schwere 5 — knifflig: eindeutig, aber nur wenige wissen es
  { kategorie: 'Kunst', frage: 'In welchem Museum hängt Botticellis Gemälde „Die Geburt der Venus"?', antworten: ['Louvre', 'Prado', 'Uffizien', 'Rijksmuseum'], richtig: 2, erklaerung: 'Die Uffizien liegen in Florenz, der Stadt, in der Botticelli lebte und arbeitete. Das Bild zeigt die Göttin auf einer Muschel.', schwere: 5 },
  { kategorie: 'Kunst', frage: 'Wer gründete 1919 in Weimar die Kunstschule Bauhaus?', antworten: ['Wassily Kandinsky', 'Paul Klee', 'Ludwig Mies van der Rohe', 'Walter Gropius'], richtig: 3, erklaerung: 'Der Architekt Walter Gropius holte Künstler wie Paul Klee und Wassily Kandinsky als Lehrer an die Schule. Später zog das Bauhaus nach Dessau.', schwere: 5 },
  { kategorie: 'Musik', frage: 'Welches Instrument stellt in Prokofjews Musikmärchen „Peter und der Wolf" die Ente dar?', antworten: ['Oboe', 'Klarinette', 'Fagott', 'Querflöte'], richtig: 0, erklaerung: 'In dem Musikmärchen hat jede Figur ihr eigenes Instrument: Der Vogel ist die Querflöte, die Katze die Klarinette und der Großvater das Fagott.', schwere: 5 },
  { kategorie: 'Musik', frage: 'Wer komponierte die Märchenoper „Hänsel und Gretel"?', antworten: ['Richard Wagner', 'Engelbert Humperdinck', 'Carl Orff', 'Albert Lortzing'], richtig: 1, erklaerung: 'Die Oper wurde 1893 in Weimar uraufgeführt. Den Text schrieb Humperdincks Schwester Adelheid Wette.', schwere: 5 },
  { kategorie: 'Musik', frage: 'Aus welcher Oper von Giuseppe Verdi stammt der berühmte Triumphmarsch?', antworten: ['Rigoletto', 'Nabucco', 'Aida', 'La Traviata'], richtig: 2, erklaerung: 'Die Oper spielt im alten Ägypten und wurde 1871 in Kairo uraufgeführt.', schwere: 5 },
  { kategorie: 'Literatur', frage: 'Wie heißt der Erzähler in Herman Melvilles Roman „Moby Dick"?', antworten: ['Ahab', 'Queequeg', 'Starbuck', 'Ismael'], richtig: 3, erklaerung: 'Der Roman beginnt im Original mit dem berühmten Satz „Call me Ishmael". Kapitän Ahab jagt darin den weißen Wal.', schwere: 5 },
  { kategorie: 'Literatur', frage: 'Wie heißt die Schildkröte von Meister Hora in Michael Endes „Momo"?', antworten: ['Kassiopeia', 'Andromeda', 'Fuchur', 'Ariadne'], richtig: 0, erklaerung: 'Kassiopeia kann eine halbe Stunde in die Zukunft sehen und verständigt sich mit Buchstaben, die auf ihrem Panzer aufleuchten.', schwere: 5 },
  { kategorie: 'Sport', frage: 'Wie nennt man beim Golf ein Loch, das mit zwei Schlägen unter Par gespielt wird?', antworten: ['Birdie', 'Eagle', 'Albatross', 'Bogey'], richtig: 1, erklaerung: 'Ein Schlag unter Par heißt Birdie, drei Schläge darunter Albatross. Par ist die vorgesehene Schlagzahl für ein Loch.', schwere: 5 },
  { kategorie: 'Sport', frage: 'Wie schwer ist die Kugel beim Kugelstoßen der Männer?', antworten: ['5,00 kg', '6,25 kg', '7,26 kg', '8,50 kg'], richtig: 2, erklaerung: 'Das entspricht genau 16 englischen Pfund. Bei den Frauen wiegt die Kugel 4 Kilogramm.', schwere: 5 },
  { kategorie: 'Essen', frage: 'Aus welcher Milch wird echter Roquefort-Käse hergestellt?', antworten: ['Kuhmilch', 'Ziegenmilch', 'Büffelmilch', 'Schafmilch'], richtig: 3, erklaerung: 'Der Blauschimmelkäse aus Südfrankreich reift in den Kalksteinhöhlen des Ortes Roquefort-sur-Soulzon.', schwere: 5 },
  { kategorie: 'Essen', frage: 'Zu welcher Pflanzenfamilie gehört die Vanille?', antworten: ['Orchideen', 'Lorbeergewächse', 'Hülsenfrüchtler', 'Rosengewächse'], richtig: 0, erklaerung: 'Die Vanilleschote ist die Frucht einer kletternden Orchidee, die ursprünglich aus Mexiko stammt.', schwere: 5 },
  { kategorie: 'Mythologie', frage: 'Wie heißt das achtbeinige Pferd des nordischen Gottes Odin?', antworten: ['Fenrir', 'Sleipnir', 'Hugin', 'Pegasus'], richtig: 1, erklaerung: 'Sleipnir gilt in der Sage als das beste aller Pferde. Odins zwei Raben heißen dagegen Hugin und Munin.', schwere: 5 },
  { kategorie: 'Mythologie', frage: 'Wie heißt der Weltenbaum der nordischen Mythologie?', antworten: ['Bifröst', 'Mjölnir', 'Yggdrasil', 'Ragnarök'], richtig: 2, erklaerung: 'Die riesige Esche verbindet in der Sage die neun Welten, darunter Asgard, die Welt der Götter, und Midgard, die Welt der Menschen.', schwere: 5 },
  { kategorie: 'Mythologie', frage: 'Wie heißt die Frau des Odysseus, die zwanzig Jahre auf seine Heimkehr wartete?', antworten: ['Helena', 'Kassandra', 'Andromache', 'Penelope'], richtig: 3, erklaerung: 'Um die vielen Männer hinzuhalten, die sie heiraten wollten, webte sie tagsüber an einem Tuch und trennte es nachts heimlich wieder auf.', schwere: 5 },
  { kategorie: 'Alltag', frage: 'Wie viele Meter hat eine Seemeile?', antworten: ['1852 m', '1000 m', '1609 m', '2000 m'], richtig: 0, erklaerung: 'Eine Seemeile entspricht einer Bogenminute entlang eines Längenkreises der Erde. Rund 1609 Meter sind dagegen eine englische Landmeile.', schwere: 5 },
  { kategorie: 'Alltag', frage: 'Wie viele Stück sind ein „Schock"?', antworten: ['12', '60', '20', '144'], richtig: 1, erklaerung: 'Ein Schock sind fünf Dutzend. Ebenso alte Zählmaße sind die Stiege mit 20 und das Gros mit 144 Stück.', schwere: 5 },
  { kategorie: 'Alltag', frage: 'Welche Maße hat ein Blatt Papier im Format DIN A4?', antworten: ['200 × 300 mm', '216 × 279 mm', '210 × 297 mm', '148 × 210 mm'], richtig: 2, erklaerung: 'Zwei A4-Blätter nebeneinander ergeben genau ein A3-Blatt. Der größte Bogen, A0, hat rund einen Quadratmeter Fläche.', schwere: 5 },
];
