/**
 * Fragen der Stufen 3 bis 5 für die Gewinnleiter: Geschichte, Erde (Länder, Hauptstädte, Flüsse,
 * Berge, Meere, Inseln) und Gesellschaft (Euro, EU, Demokratie, Wirtschaft). Reine Daten.
 *
 * Nur Fakten mit unstrittiger Antwort: keine Einwohnerzahlen, keine amtierenden Personen, keine
 * Länder mit mehreren Hauptstädten, Jahreszahlen nur bei Ereignissen mit festem Jahr.
 */
import type { LeiterFrage } from '../../core/leiter';

export const FRAGEN_SCHWER_WELT: readonly LeiterFrage[] = [
  // ── Schwere 3 ─────────────────────────────────────────────────────────────
  { kategorie: 'Geschichte', frage: 'Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', antworten: ['Willy Brandt', 'Konrad Adenauer', 'Ludwig Erhard', 'Helmut Schmidt'], richtig: 1, erklaerung: 'Konrad Adenauer war von 1949 bis 1963 Bundeskanzler. Bei seinem Amtsantritt war er bereits 73 Jahre alt.', schwere: 3 },
  { kategorie: 'Geschichte', frage: 'Welches Volk erbaute die Bergstadt Machu Picchu im heutigen Peru?', antworten: ['Azteken', 'Maya', 'Inka', 'Olmeken'], richtig: 2, erklaerung: 'Machu Picchu wurde im 15. Jahrhundert von den Inka erbaut und gehört heute zum UNESCO-Welterbe.', schwere: 3 },
  { kategorie: 'Geschichte', frage: 'Welcher Pharao wurde berühmt, weil sein fast unberührtes Grab 1922 entdeckt wurde?', antworten: ['Tutanchamun', 'Ramses II.', 'Cheops', 'Echnaton'], richtig: 0, erklaerung: 'Das Grab des jungen Pharaos Tutanchamun im Tal der Könige war kaum geplündert. Berühmt ist vor allem seine goldene Totenmaske.', schwere: 3 },
  { kategorie: 'Geschichte', frage: 'Welche römische Stadt wurde im Jahr 79 n. Chr. beim Ausbruch des Vesuvs verschüttet?', antworten: ['Ostia', 'Neapel', 'Syrakus', 'Pompeji'], richtig: 3, erklaerung: 'Die Asche hat Pompeji fast 1700 Jahre lang konserviert. Heute kann man dort Straßen, Häuser und Wandmalereien besichtigen.', schwere: 3 },
  { kategorie: 'Geschichte', frage: 'Welcher König ließ das Schloss Neuschwanstein erbauen?', antworten: ['Ludwig I.', 'Maximilian II.', 'Ludwig II.', 'Friedrich der Große'], richtig: 2, erklaerung: 'Der bayerische König Ludwig II. ließ Neuschwanstein ab 1869 bauen. Er starb 1886, bevor das Schloss fertig war.', schwere: 3 },
  { kategorie: 'Geschichte', frage: 'Wer entwickelte um 1450 in Europa den Buchdruck mit beweglichen Metall-Lettern?', antworten: ['Martin Luther', 'Albrecht Dürer', 'Johannes Kepler', 'Johannes Gutenberg'], richtig: 3, erklaerung: 'Johannes Gutenberg aus Mainz druckte unter anderem die berühmte Gutenberg-Bibel. Vorher mussten Bücher meist mühsam von Hand abgeschrieben werden.', schwere: 3 },
  { kategorie: 'Geschichte', frage: 'Wer flog 1961 als erster Mensch in den Weltraum?', antworten: ['Neil Armstrong', 'Juri Gagarin', 'John Glenn', 'Alan Shepard'], richtig: 1, erklaerung: 'Der sowjetische Kosmonaut Juri Gagarin umrundete am 12. April 1961 einmal die Erde. Sein Flug dauerte nur etwa 108 Minuten.', schwere: 3 },
  { kategorie: 'Erde', frage: 'Wie heißt die Hauptstadt von Portugal?', antworten: ['Lissabon', 'Porto', 'Faro', 'Coimbra'], richtig: 0, erklaerung: 'Lissabon liegt an der Mündung des Tejo in den Atlantik und ist die westlichste Hauptstadt auf dem europäischen Festland.', schwere: 3 },
  { kategorie: 'Erde', frage: 'Welcher Fluss fließt durch Paris?', antworten: ['Loire', 'Rhone', 'Seine', 'Garonne'], richtig: 2, erklaerung: 'Die Seine fließt mitten durch Paris und mündet bei Le Havre in den Ärmelkanal. In Paris führen Dutzende Brücken über sie.', schwere: 3 },
  { kategorie: 'Erde', frage: 'Welches ist die größte Insel der Erde?', antworten: ['Grönland', 'Madagaskar', 'Borneo', 'Neuguinea'], richtig: 0, erklaerung: 'Grönland ist über zwei Millionen Quadratkilometer groß und größtenteils von Eis bedeckt. Australien zählt nicht als Insel, sondern als Kontinent.', schwere: 3 },
  { kategorie: 'Erde', frage: 'Welches Gebirge zieht sich an der Westküste Südamerikas entlang?', antworten: ['Rocky Mountains', 'Himalaya', 'Atlas', 'Anden'], richtig: 3, erklaerung: 'Die Anden sind rund 7000 Kilometer lang und damit das längste Gebirge auf dem Festland der Erde.', schwere: 3 },
  { kategorie: 'Erde', frage: 'Wie heißt die Landeshauptstadt von Nordrhein-Westfalen?', antworten: ['Köln', 'Düsseldorf', 'Dortmund', 'Essen'], richtig: 1, erklaerung: 'Düsseldorf am Rhein ist Landeshauptstadt, obwohl Köln die größte Stadt des Landes ist.', schwere: 3 },
  { kategorie: 'Erde', frage: 'Welcher Berg ist der höchste Afrikas?', antworten: ['Mount Kenya', 'Toubkal', 'Kilimandscharo', 'Mount Stanley'], richtig: 2, erklaerung: 'Der Kilimandscharo in Tansania ist knapp 5900 Meter hoch. Er ist ein Vulkan und steht für sich allein, nicht in einer langen Gebirgskette.', schwere: 3 },
  { kategorie: 'Gesellschaft', frage: 'Wie viele Sterne hat die Flagge der Europäischen Union?', antworten: ['10', '12', '15', '27'], richtig: 1, erklaerung: 'Die zwölf goldenen Sterne stehen für Einheit und Vollkommenheit. Ihre Zahl hängt nicht davon ab, wie viele Länder Mitglied sind.', schwere: 3 },
  { kategorie: 'Gesellschaft', frage: 'In welchem Jahr wurden in Deutschland Euro-Münzen und -Scheine eingeführt?', antworten: ['1996', '1999', '2002', '2005'], richtig: 2, erklaerung: 'Seit dem 1. Januar 2002 bezahlt man in Deutschland mit Euro-Bargeld. Als Buchgeld, etwa für Überweisungen, gab es den Euro schon seit 1999.', schwere: 3 },
  { kategorie: 'Gesellschaft', frage: 'Was bedeutet Inflation?', antworten: ['Die Preise steigen allgemein', 'Die Preise sinken allgemein', 'Die Löhne werden eingefroren', 'Die Zinsen fallen auf null'], richtig: 0, erklaerung: 'Bei einer Inflation kann man mit demselben Geld nach und nach weniger kaufen. Sinken die Preise allgemein, nennt man das Deflation.', schwere: 3 },
  { kategorie: 'Gesellschaft', frage: 'Wer ist laut Grundgesetz das Staatsoberhaupt Deutschlands?', antworten: ['Der Bundeskanzler', 'Der Bundestagspräsident', 'Der Präsident des Verfassungsgerichts', 'Der Bundespräsident'], richtig: 3, erklaerung: 'Der Bundespräsident vertritt Deutschland nach außen und unterzeichnet die Gesetze. Die Regierung führt dagegen der Bundeskanzler.', schwere: 3 },

  // ── Schwere 4 ─────────────────────────────────────────────────────────────
  { kategorie: 'Geschichte', frage: 'In welchem Jahr begann die Französische Revolution?', antworten: ['1776', '1789', '1804', '1815'], richtig: 1, erklaerung: 'Am 14. Juli 1789 stürmten Pariser Bürger die Bastille, ein Gefängnis. Der 14. Juli ist bis heute der französische Nationalfeiertag.', schwere: 4 },
  { kategorie: 'Geschichte', frage: 'In welchem Jahr wurde Karl der Große in Rom zum Kaiser gekrönt?', antworten: ['800', '768', '814', '843'], richtig: 0, erklaerung: 'Papst Leo III. setzte Karl dem Großen am Weihnachtstag des Jahres 800 die Kaiserkrone auf. Karl herrschte über weite Teile West- und Mitteleuropas.', schwere: 4 },
  { kategorie: 'Geschichte', frage: 'Welcher Seefahrer erreichte 1498 als erster Europäer auf dem Seeweg um Afrika Indien?', antworten: ['Bartolomeu Dias', 'Vasco da Gama', 'Ferdinand Magellan', 'James Cook'], richtig: 1, erklaerung: 'Vasco da Gama segelte von Portugal um das Kap der Guten Hoffnung bis nach Kalikut in Indien. Damit war der Seeweg nach Asien gefunden.', schwere: 4 },
  { kategorie: 'Geschichte', frage: 'Wer erreichte 1911 als Erster den Südpol?', antworten: ['Robert Falcon Scott', 'Ernest Shackleton', 'Fridtjof Nansen', 'Roald Amundsen'], richtig: 3, erklaerung: 'Der Norweger Roald Amundsen kam am 14. Dezember 1911 am Südpol an, etwa einen Monat vor dem Briten Robert Falcon Scott.', schwere: 4 },
  { kategorie: 'Geschichte', frage: 'Auf welcher Burg übersetzte Martin Luther das Neue Testament ins Deutsche?', antworten: ['Wartburg', 'Burg Eltz', 'Burg Hohenzollern', 'Reichsburg Cochem'], richtig: 0, erklaerung: 'Luther lebte 1521/22 versteckt als „Junker Jörg“ auf der Wartburg bei Eisenach. Seine Übersetzung erschien 1522 als „Septembertestament“.', schwere: 4 },
  { kategorie: 'Geschichte', frage: 'Wer wurde 1871 der erste Reichskanzler des Deutschen Kaiserreichs?', antworten: ['Otto von Bismarck', 'Paul von Hindenburg', 'Leo von Caprivi', 'Gustav Stresemann'], richtig: 0, erklaerung: 'Otto von Bismarck war von 1871 bis 1890 Reichskanzler. Wegen seiner Durchsetzungskraft nannte man ihn den „Eisernen Kanzler“.', schwere: 4 },
  { kategorie: 'Geschichte', frage: 'Auf welcher Insel starb Napoleon Bonaparte 1821 in der Verbannung?', antworten: ['Elba', 'Korsika', 'St. Helena', 'Sardinien'], richtig: 2, erklaerung: 'Nach Waterloo 1815 wurde Napoleon auf die abgelegene Atlantikinsel St. Helena gebracht. Von Elba, wohin er vorher verbannt war, konnte er noch fliehen.', schwere: 4 },
  { kategorie: 'Erde', frage: 'Wie heißt die Hauptstadt von Australien?', antworten: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], richtig: 2, erklaerung: 'Canberra wurde eigens als Hauptstadt geplant, weil sich Sydney und Melbourne nicht einigen konnten, welche der beiden Städte es werden sollte.', schwere: 4 },
  { kategorie: 'Erde', frage: 'Wie heißt die Hauptstadt der Türkei?', antworten: ['Istanbul', 'Ankara', 'Izmir', 'Antalya'], richtig: 1, erklaerung: 'Seit 1923 ist Ankara die Hauptstadt der Türkei. Istanbul ist zwar die größte Stadt des Landes, aber nicht die Hauptstadt.', schwere: 4 },
  { kategorie: 'Erde', frage: 'In welches Meer mündet die Donau?', antworten: ['Nordsee', 'Ostsee', 'Schwarzes Meer', 'Mittelmeer'], richtig: 2, erklaerung: 'Die Donau entspringt im Schwarzwald und mündet nach rund 2850 Kilometern in einem großen Delta ins Schwarze Meer.', schwere: 4 },
  { kategorie: 'Erde', frage: 'Welches ist die größte Insel im Mittelmeer?', antworten: ['Sardinien', 'Zypern', 'Korsika', 'Sizilien'], richtig: 3, erklaerung: 'Sizilien gehört zu Italien und ist gut 25.000 Quadratkilometer groß. Knapp dahinter folgt Sardinien.', schwere: 4 },
  { kategorie: 'Erde', frage: 'Welcher See ist der tiefste der Erde?', antworten: ['Baikalsee', 'Tanganjikasee', 'Victoriasee', 'Ladogasee'], richtig: 0, erklaerung: 'Der Baikalsee in Sibirien ist über 1600 Meter tief. Er enthält mehr Wasser als jeder andere Süßwassersee der Erde.', schwere: 4 },
  { kategorie: 'Erde', frage: 'Nach welchem Londoner Stadtteil ist der Nullmeridian benannt?', antworten: ['Westminster', 'Greenwich', 'Kensington', 'Camden'], richtig: 1, erklaerung: 'Durch die Sternwarte in Greenwich verläuft der Nullmeridian, von dem aus die Längengrade gezählt werden. Er wurde 1884 international festgelegt.', schwere: 4 },
  { kategorie: 'Erde', frage: 'Wie viele Nachbarländer hat Deutschland?', antworten: ['7', '8', '9', '10'], richtig: 2, erklaerung: 'Deutschland grenzt an Dänemark, Polen, Tschechien, Österreich, die Schweiz, Frankreich, Luxemburg, Belgien und die Niederlande.', schwere: 4 },
  { kategorie: 'Gesellschaft', frage: 'In welcher Stadt hat die Europäische Zentralbank ihren Sitz?', antworten: ['Brüssel', 'Luxemburg', 'Paris', 'Frankfurt am Main'], richtig: 3, erklaerung: 'Die Europäische Zentralbank in Frankfurt am Main ist für den Euro zuständig. Sie soll vor allem dafür sorgen, dass die Preise stabil bleiben.', schwere: 4 },
  { kategorie: 'Gesellschaft', frage: 'Wer wählt in Deutschland den Bundeskanzler?', antworten: ['Der Bundesrat', 'Der Bundestag', 'Die Bundesversammlung', 'Das Volk direkt'], richtig: 1, erklaerung: 'Der Bundeskanzler wird auf Vorschlag des Bundespräsidenten vom Bundestag gewählt. Die Bürger bestimmen ihn also nur indirekt, über die Abgeordneten.', schwere: 4 },
  { kategorie: 'Gesellschaft', frage: 'Wie nennt man die Aufteilung der Staatsmacht auf Parlament, Regierung und Gerichte?', antworten: ['Föderalismus', 'Subsidiarität', 'Sozialstaat', 'Gewaltenteilung'], richtig: 3, erklaerung: 'Durch die Gewaltenteilung kontrollieren sich gesetzgebende, ausführende und rechtsprechende Gewalt gegenseitig. So kann niemand alle Macht allein ausüben.', schwere: 4 },

  // ── Schwere 5 ─────────────────────────────────────────────────────────────
  { kategorie: 'Geschichte', frage: 'In welchem Jahr eroberten die Osmanen Konstantinopel?', antworten: ['1389', '1453', '1517', '1571'], richtig: 1, erklaerung: 'Mit dem Fall von Konstantinopel 1453 endete das Byzantinische Reich. Die Stadt heißt heute Istanbul.', schwere: 5 },
  { kategorie: 'Geschichte', frage: 'Wer wurde 1871 im Spiegelsaal von Versailles zum Deutschen Kaiser ausgerufen?', antworten: ['Wilhelm I.', 'Wilhelm II.', 'Friedrich III.', 'Friedrich Wilhelm IV.'], richtig: 0, erklaerung: 'Der preußische König Wilhelm I. wurde am 18. Januar 1871 zum Deutschen Kaiser proklamiert. Damit war das Deutsche Kaiserreich gegründet.', schwere: 5 },
  { kategorie: 'Geschichte', frage: 'Wer war der erste Reichspräsident der Weimarer Republik?', antworten: ['Paul von Hindenburg', 'Gustav Stresemann', 'Friedrich Ebert', 'Walther Rathenau'], richtig: 2, erklaerung: 'Friedrich Ebert war von 1919 bis zu seinem Tod 1925 Reichspräsident. Danach wurde Paul von Hindenburg gewählt.', schwere: 5 },
  { kategorie: 'Geschichte', frage: 'Welcher berühmte Philosoph war der Lehrer Alexanders des Großen?', antworten: ['Platon', 'Sokrates', 'Aristoteles', 'Pythagoras'], richtig: 2, erklaerung: 'Aristoteles unterrichtete den jungen Alexander einige Jahre lang in Makedonien. Er selbst war zuvor ein Schüler Platons gewesen.', schwere: 5 },
  { kategorie: 'Geschichte', frage: 'Welcher Wikinger erreichte um das Jahr 1000 Nordamerika – lange vor Kolumbus?', antworten: ['Harald Blauzahn', 'Leif Eriksson', 'Knut der Große', 'Olaf Tryggvason'], richtig: 1, erklaerung: 'Leif Eriksson segelte von Grönland aus nach Westen und nannte das Land, das er fand, „Vinland“. In Neufundland wurden Reste einer Wikingersiedlung entdeckt.', schwere: 5 },
  { kategorie: 'Geschichte', frage: 'Zu welcher Herrscherfamilie gehörte die berühmte Königin Kleopatra, die zur Zeit Caesars über Ägypten herrschte?', antworten: ['Ptolemäer', 'Ramessiden', 'Julier', 'Achämeniden'], richtig: 0, erklaerung: 'Die Ptolemäer stammten aus Makedonien und regierten Ägypten nach dem Tod Alexanders des Großen knapp 300 Jahre lang.', schwere: 5 },
  { kategorie: 'Geschichte', frage: 'Welcher Politiker gilt als „Vater des Wirtschaftswunders“ in Westdeutschland?', antworten: ['Ludwig Erhard', 'Theodor Heuss', 'Kurt Georg Kiesinger', 'Walter Scheel'], richtig: 0, erklaerung: 'Ludwig Erhard war ab 1949 Wirtschaftsminister und gilt als Wegbereiter der sozialen Marktwirtschaft. Von 1963 bis 1966 war er Bundeskanzler.', schwere: 5 },
  { kategorie: 'Erde', frage: 'Wie heißt die Hauptstadt von Marokko?', antworten: ['Casablanca', 'Marrakesch', 'Rabat', 'Fès'], richtig: 2, erklaerung: 'Rabat liegt an der Atlantikküste und ist Sitz von König und Regierung. Casablanca ist zwar die größte Stadt Marokkos, aber nicht die Hauptstadt.', schwere: 5 },
  { kategorie: 'Erde', frage: 'Wie heißt die Hauptstadt von Nigeria?', antworten: ['Lagos', 'Kano', 'Ibadan', 'Abuja'], richtig: 3, erklaerung: 'Abuja wurde als neue Hauptstadt in der Landesmitte geplant und löste 1991 Lagos ab. Lagos an der Küste ist aber weiterhin die größte Stadt.', schwere: 5 },
  { kategorie: 'Erde', frage: 'Welcher Berg ist der höchste Südamerikas?', antworten: ['Chimborazo', 'Huascarán', 'Aconcagua', 'Cotopaxi'], richtig: 2, erklaerung: 'Der Aconcagua in Argentinien ist fast 7000 Meter hoch. Er ist der höchste Berg außerhalb Asiens.', schwere: 5 },
  { kategorie: 'Erde', frage: 'Welcher Fluss ist der längste Europas?', antworten: ['Donau', 'Wolga', 'Dnepr', 'Rhein'], richtig: 1, erklaerung: 'Die Wolga fließt rund 3500 Kilometer durch Russland und mündet ins Kaspische Meer. Die Donau ist der zweitlängste Fluss Europas.', schwere: 5 },
  { kategorie: 'Erde', frage: 'In welchem Land liegt die antike Felsenstadt Petra?', antworten: ['Jordanien', 'Ägypten', 'Syrien', 'Libanon'], richtig: 0, erklaerung: 'Die Nabatäer meißelten in Petra Gräber und Tempel direkt in die rötlichen Sandsteinfelsen. Seit 1985 gehört die Stadt zum UNESCO-Welterbe.', schwere: 5 },
  { kategorie: 'Erde', frage: 'Zu welchem Land gehört die Osterinsel mit ihren riesigen Steinfiguren?', antworten: ['Chile', 'Peru', 'Neuseeland', 'Frankreich'], richtig: 0, erklaerung: 'Die Osterinsel liegt mitten im Pazifik, über 3500 Kilometer vor der Küste Chiles. Ihre Steinfiguren heißen Moai.', schwere: 5 },
  { kategorie: 'Erde', frage: 'Welcher ist der größte See, der vollständig in Deutschland liegt?', antworten: ['Chiemsee', 'Müritz', 'Starnberger See', 'Steinhuder Meer'], richtig: 1, erklaerung: 'Die Müritz in Mecklenburg-Vorpommern ist über 100 Quadratkilometer groß. Der Bodensee ist zwar größer, liegt aber auch in Österreich und der Schweiz.', schwere: 5 },
  { kategorie: 'Gesellschaft', frage: 'Wer wählt in Deutschland den Bundespräsidenten?', antworten: ['Das Volk direkt', 'Der Bundestag', 'Der Bundesrat', 'Die Bundesversammlung'], richtig: 3, erklaerung: 'Die Bundesversammlung besteht aus allen Bundestagsabgeordneten und ebenso vielen Vertretern der Länder. Sie tritt nur zusammen, um den Bundespräsidenten zu wählen.', schwere: 5 },
  { kategorie: 'Gesellschaft', frage: 'In welcher Stadt hat der Internationale Gerichtshof der Vereinten Nationen seinen Sitz?', antworten: ['Genf', 'Straßburg', 'New York', 'Den Haag'], richtig: 3, erklaerung: 'Der Internationale Gerichtshof im Friedenspalast von Den Haag entscheidet Streitigkeiten zwischen Staaten. Er ist das wichtigste Gericht der Vereinten Nationen.', schwere: 5 },
  { kategorie: 'Gesellschaft', frage: 'Wie viele Staaten gründeten 1957 die Europäische Wirtschaftsgemeinschaft (EWG)?', antworten: ['4', '9', '12', '6'], richtig: 3, erklaerung: 'Gründer waren Belgien, die Bundesrepublik Deutschland, Frankreich, Italien, Luxemburg und die Niederlande. Aus der EWG ging später die Europäische Union hervor.', schwere: 5 },
];
