import type { LeiterFrage } from '../../core/leiter';

/**
 * Rechtschreib- und Grammatikfragen für die oberen Stufen der Leiter (Schwere 3 bis 5).
 *
 * Bewusst nur Wörter mit **einer** zulässigen Schreibweise: Wo das amtliche Regelwerk zwei Formen
 * erlaubt (Joghurt/Jogurt, Delfin/Delphin …), würde ein Kind für richtiges Wissen bestraft. Aus
 * demselben Grund keine Wörter mit ß gegen ss — in der Schweiz ist „ss" überall zulässig. Kein Wort
 * hier steht schon in `woerter.ts`.
 */
export const WORTFRAGEN_SCHREIBUNG: readonly LeiterFrage[] = [
  // Rechtschreibung — Schwere 3
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['wahrscheinlich', 'warscheinlich', 'wahrscheinlig', 'wahrschainlich'], richtig: 0, erklaerung: 'Im Wort steckt „wahr" — deshalb mit Dehnungs-h. Am Ende steht „-lich", nicht „-lig".', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['nemlich', 'nämlich', 'nähmlich', 'nämlig'], richtig: 1, erklaerung: '„nämlich" ist mit „Name" verwandt: deshalb „ä" und kein Dehnungs-h. Am Ende steht „-lich".', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['fielleicht', 'vieleicht', 'vielleicht', 'vielleich'], richtig: 2, erklaerung: 'Zusammengewachsen aus „viel" und „leicht" — deshalb zwei „l" in der Mitte und ein „t" am Ende.', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['zimlich', 'ziehmlich', 'ziemlig', 'ziemlich'], richtig: 3, erklaerung: 'Das lange „i" wird hier als „ie" geschrieben, ohne zusätzliches h. Am Ende steht „-lich".', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Gebäude', 'Gebeude', 'Gebäute', 'Geboide'], richtig: 0, erklaerung: '„Gebäude" kommt von „bauen": Aus „au" wird „äu", nicht „eu" oder „oi".', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Ereigniss', 'Ereignis', 'Ereichnis', 'Ereigniß'], richtig: 1, erklaerung: 'Wörter auf „-nis" enden in der Einzahl mit einem einzigen „s". Erst in der Mehrzahl wird es doppelt: Ereignisse.', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Fluß', 'Flus', 'Fluss', 'Fluhs'], richtig: 2, erklaerung: 'Nach kurzem Vokal steht „ss". Die Schreibung „Fluß" ist seit der Rechtschreibreform veraltet.', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['gefärlich', 'gefehrlich', 'gefährlig', 'gefährlich'], richtig: 3, erklaerung: 'Kommt von „Gefahr": Aus „a" wird „ä", und das Dehnungs-h bleibt erhalten.', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Rätsel', 'Rätzel', 'Retsel', 'Rättsel'], richtig: 0, erklaerung: '„Rätsel" ist mit „raten" verwandt — deshalb „ä". In der Mitte steht „ts", kein „tz" und kein „tts".', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Machine', 'Maschine', 'Maschiene', 'Maschinne'], richtig: 1, erklaerung: 'Ein Fremdwort aus dem Französischen: Das lange „i" wird ohne „e" geschrieben, wie bei „Medizin" oder „Benzin".', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Packet', 'Pakett', 'Paket', 'Packett'], richtig: 2, erklaerung: 'Nur ein „k" in der Mitte und ein einfaches „t" am Ende — kein „ck" und kein „tt".', schwere: 3 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['allmälich', 'almählich', 'allmählig', 'allmählich'], richtig: 3, erklaerung: 'Doppel-l am Anfang, Dehnungs-h nach dem „ä" und am Ende „-lich": all-mäh-lich.', schwere: 3 },

  // Rechtschreibung — Schwere 4
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Reparatur', 'Reperatur', 'Repparatur', 'Reparattur'], richtig: 0, erklaerung: 'Verwandt mit „reparieren" — deshalb „Repa-", nicht „Repe-". Der Fehler „Reperatur" ist sehr verbreitet.', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Interresse', 'Interesse', 'Intresse', 'Interese'], richtig: 1, erklaerung: 'Aus dem Lateinischen „interesse": nur ein „r" in der Mitte, dafür „ss" vor dem Schluss-e.', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Athmosphäre', 'Atmosfäre', 'Atmosphäre', 'Atmosphere'], richtig: 2, erklaerung: 'Aus dem Griechischen „atmós" (Dampf) und „sphaira" (Kugel): kein „h" nach dem „t", aber „ph" und am Ende „ä".', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Labürinth', 'Labyrint', 'Laberinth', 'Labyrinth'], richtig: 3, erklaerung: 'Ein Wort aus dem Griechischen: mit „y" in der Mitte und „th" am Ende.', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Charakter', 'Karakter', 'Charackter', 'Character'], richtig: 0, erklaerung: 'Aus dem Griechischen: vorn „Ch", gesprochen wie „k". In der Mitte steht ein einfaches „k" — kein „ck" und kein „c" wie im Englischen.', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Dedektiv', 'Detektiv', 'Detecktiv', 'Detektif'], richtig: 1, erklaerung: 'Geht auf das lateinische „detegere" (aufdecken) zurück — darum zweimal „t": De-tek-tiv. Am Ende „-iv" mit „v".', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Kanditat', 'Candidat', 'Kandidat', 'Kandidaat'], richtig: 2, erklaerung: 'Erst „d", dann noch einmal „d": Kan-di-dat. Das Wort kommt vom lateinischen „candidatus".', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Wiederspruch', 'Widerspruck', 'Wiedersprug', 'Widerspruch'], richtig: 3, erklaerung: '„wider" heißt „gegen" und wird ohne „e" geschrieben. „wieder" mit „ie" bedeutet „noch einmal".', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Karussell', 'Karusell', 'Karrussell', 'Karussel'], richtig: 0, erklaerung: 'Ein einfaches „r", ein doppeltes „s" und am Ende ein doppeltes „l": Ka-rus-sell.', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['entgültig', 'endgültig', 'endgiltig', 'endgültich'], richtig: 1, erklaerung: 'Hier steckt „Ende" drin — also „end-" mit „d". Die Vorsilbe „ent-" wie in „entdecken" passt nicht.', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Terasse', 'Terrase', 'Terrasse', 'Tärrasse'], richtig: 2, erklaerung: 'Geht auf das lateinische „terra" (Erde) zurück — darum zwei „r". Am Ende steht dazu „ss".', schwere: 4 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Känguruh', 'Kenguru', 'Kängeru', 'Känguru'], richtig: 3, erklaerung: 'Seit der Rechtschreibreform ohne „h" am Ende, wie „Gnu" oder „Kakadu". „Känguruh" ist veraltet.', schwere: 4 },

  // Rechtschreibung — Schwere 5
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Entgelt', 'Entgeld', 'Endgeld', 'Endgelt'], richtig: 0, erklaerung: 'Kommt von „entgelten" (bezahlen, vergüten), nicht von „Geld" — darum vorn „ent-" und am Ende „t".', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Lapalie', 'Lappalie', 'Lappali', 'Lapallie'], richtig: 1, erklaerung: 'Gebildet aus „Lappen" (wertloser Fetzen) mit lateinisch klingender Endung — deshalb „pp", aber nur ein „l".', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Sattelit', 'Satelit', 'Satellit', 'Sattellit'], richtig: 2, erklaerung: 'Ein einfaches „t" vorn, ein doppeltes „l" in der Mitte: Sa-tel-lit. Mit dem „Sattel" hat das Wort nichts zu tun.', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Dilletant', 'Dillettant', 'Dilettannt', 'Dilettant'], richtig: 3, erklaerung: 'Aus dem Italienischen „dilettante": ein einfaches „l", aber ein doppeltes „t" — Di-let-tant.', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Gelatine', 'Gelantine', 'Gelatiene', 'Gellatine'], richtig: 0, erklaerung: 'Kein „n" vor dem „t", auch wenn man es oft so hört. Das Wort geht auf das lateinische „gelatus" (gefroren) zurück.', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Standart', 'Standard', 'Standardt', 'Stantard'], richtig: 1, erklaerung: 'Am Ende steht „d" wie im englischen „standard". Mit dem Wort „Art" hat es nichts zu tun.', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['paralell', 'parralel', 'parallel', 'parallell'], richtig: 2, erklaerung: 'Ein „r", dann „ll" in der Mitte und ein einzelnes „l" am Ende: pa-ral-lel.', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Seriösität', 'Serösität', 'Seriositet', 'Seriosität'], richtig: 3, erklaerung: 'Das Adjektiv heißt „seriös", das Nomen aber „Seriosität" — ohne Umlaut, wie bei „nervös – Nervosität" oder „religiös – Religiosität".', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Stengel', 'Stängel', 'Stängl', 'Stänkel'], richtig: 1, erklaerung: 'Seit der Rechtschreibreform mit „ä", weil das Wort zu „Stange" gehört. „Stengel" ist veraltet.', schwere: 5 },
  { kategorie: 'Rechtschreibung', frage: 'Welches Wort ist richtig geschrieben?', antworten: ['Roheit', 'Rohheid', 'Rohheit', 'Rohkeit'], richtig: 2, erklaerung: 'Aus „roh" und „-heit" — beide Teile bleiben vollständig, also zwei „h". „Roheit" war die Schreibung vor der Reform.', schwere: 5 },

  // Grammatik — Schwere 3
  { kategorie: 'Grammatik', frage: 'Wie lautet die Mehrzahl von „Museum"?', antworten: ['Museen', 'Museums', 'Musea', 'Museumen'], richtig: 0, erklaerung: 'Viele Wörter auf „-um" aus dem Lateinischen bilden die Mehrzahl auf „-en": Museum – Museen, Zentrum – Zentren.', schwere: 3 },
  { kategorie: 'Grammatik', frage: 'Wie lautet das Partizip II von „schwimmen"?', antworten: ['geschwimmt', 'geschwommen', 'geschwammen', 'geschwummen'], richtig: 1, erklaerung: '„schwimmen" ist ein starkes Verb und ändert seinen Stammvokal: schwimmen – schwamm – geschwommen.', schwere: 3 },
  { kategorie: 'Grammatik', frage: 'Wie lautet das Präteritum von „bringen" (ich …)?', antworten: ['bringte', 'brang', 'brachte', 'brung'], richtig: 2, erklaerung: '„bringen" ist unregelmäßig: bringen – brachte – gebracht. Genauso geht „denken – dachte – gedacht".', schwere: 3 },
  { kategorie: 'Grammatik', frage: 'Welchen Fall verlangt die Präposition „mit"?', antworten: ['Genitiv', 'Akkusativ', 'Nominativ', 'Dativ'], richtig: 3, erklaerung: '„mit" verlangt immer den Dativ: mit dem Hund, mit der Katze, mit den Kindern.', schwere: 3 },
  { kategorie: 'Grammatik', frage: 'Zu welcher Wortart gehört „und"?', antworten: ['Konjunktion', 'Präposition', 'Adverb', 'Pronomen'], richtig: 0, erklaerung: '„und" verbindet Wörter, Satzteile oder ganze Sätze. Solche Bindewörter heißen Konjunktionen.', schwere: 3 },
  { kategorie: 'Grammatik', frage: 'Welches dieser Nomen hat den Artikel „der"?', antworten: ['Lineal', 'Spinat', 'Brille', 'Sofa'], richtig: 1, erklaerung: 'Es heißt „der Spinat", aber „das Lineal", „die Brille" und „das Sofa". Den Artikel lernt man am besten mit jedem Nomen mit.', schwere: 3 },
  { kategorie: 'Grammatik', frage: 'Welches Satzglied ist „dem Mann" im Satz „Ich gebe dem Mann das Buch."?', antworten: ['Akkusativobjekt', 'Subjekt', 'Dativobjekt', 'Prädikat'], richtig: 2, erklaerung: 'Man fragt: „Wem gebe ich das Buch?" — „dem Mann". Ein Satzglied, das auf „Wem?" antwortet, ist ein Dativobjekt.', schwere: 3 },
  { kategorie: 'Grammatik', frage: 'Wie lautet die Mehrzahl von „Bank", wenn das Geldinstitut gemeint ist?', antworten: ['Bänke', 'Banks', 'Banke', 'Banken'], richtig: 3, erklaerung: 'Die Sitzbank hat die Mehrzahl „Bänke", das Geldinstitut „Banken". Gleiches Wort, zwei Bedeutungen, zwei Mehrzahlformen.', schwere: 3 },

  // Grammatik — Schwere 4
  { kategorie: 'Grammatik', frage: 'Wie lautet die Befehlsform (Imperativ) von „essen", wenn man eine Person duzt?', antworten: ['iss!', 'ess!', 'esse!', 'isse!'], richtig: 0, erklaerung: 'Verben, die von „e" zu „i" wechseln (du isst), bilden die Befehlsform mit „i" und ohne Endung: iss!, gib!, nimm!, lies!', schwere: 4 },
  { kategorie: 'Grammatik', frage: 'Wie lautet der Superlativ von „nah"?', antworten: ['am nahsten', 'am nächsten', 'am nähesten', 'am nahesten'], richtig: 1, erklaerung: 'Die Steigerung ist unregelmäßig: nah – näher – am nächsten. Ähnlich: hoch – höher – am höchsten.', schwere: 4 },
  { kategorie: 'Grammatik', frage: 'Wie lautet der Genitiv von „der Name"?', antworten: ['des Names', 'des Namen', 'des Namens', 'des Nameses'], richtig: 2, erklaerung: 'Einige Nomen bekommen im Genitiv „-ns": des Namens, des Glaubens, des Willens, des Gedankens.', schwere: 4 },
  { kategorie: 'Grammatik', frage: 'In welcher Zeitform steht der Satz „Ich hatte gegessen."?', antworten: ['Perfekt', 'Präteritum', 'Futur II', 'Plusquamperfekt'], richtig: 3, erklaerung: '„hatte" oder „war" plus Partizip II ergibt das Plusquamperfekt — die Vorvergangenheit, also was noch vor etwas anderem Vergangenen geschah.', schwere: 4 },
  { kategorie: 'Grammatik', frage: 'Welche Form passt? „Ich frage den ___." (Polizist)', antworten: ['Polizisten', 'Polizist', 'Polizists', 'Polizistes'], richtig: 0, erklaerung: '„Polizist" endet außer im Nominativ Einzahl immer auf „-en": den Polizisten, dem Polizisten, des Polizisten.', schwere: 4 },
  { kategorie: 'Grammatik', frage: '„Ich gehe in den Garten." Welchen Fall verlangt „in" in diesem Satz?', antworten: ['Dativ', 'Akkusativ', 'Genitiv', 'Nominativ'], richtig: 1, erklaerung: '„in" kann Dativ oder Akkusativ verlangen. Bei einer Richtung (Wohin?) steht der Akkusativ, bei einem Ort (Wo?) der Dativ.', schwere: 4 },
  { kategorie: 'Grammatik', frage: 'Wie lautet die Mehrzahl von „Saal"?', antworten: ['Saale', 'Säale', 'Säle', 'Saals'], richtig: 2, erklaerung: 'In der Mehrzahl kommt ein Umlaut dazu, und dabei wird aus „aa" ein einzelnes „ä": Säle. Ein doppeltes „ä" gibt es nicht.', schwere: 4 },
  { kategorie: 'Grammatik', frage: 'Welches Satzglied ist „morgen" im Satz „Wir fahren morgen weg."?', antworten: ['Subjekt', 'Akkusativobjekt', 'Prädikat', 'Adverbiale Bestimmung'], richtig: 3, erklaerung: '„morgen" antwortet auf die Frage „Wann?". Angaben zu Zeit, Ort, Art und Weise oder Grund heißen adverbiale Bestimmungen.', schwere: 4 },

  // Grammatik — Schwere 5
  { kategorie: 'Grammatik', frage: 'Welche Form passt? „Das Bild ___ gestern noch an der Wand."', antworten: ['hing', 'hängte', 'hangte', 'hung'], richtig: 0, erklaerung: 'Ohne Objekt (etwas hängt irgendwo) heißt es „hing". „hängte" braucht ein Objekt: Sie hängte das Bild an die Wand.', schwere: 5 },
  { kategorie: 'Grammatik', frage: 'Welche Form passt? „Du hast mich gestern sehr ___." (erschrecken)', antworten: ['erschrocken', 'erschreckt', 'erschrak', 'erschrocht'], richtig: 1, erklaerung: 'Wer einem anderen Angst macht, hat ihn „erschreckt". „erschrocken" gehört zum Verb ohne Objekt: Ich bin erschrocken.', schwere: 5 },
  { kategorie: 'Grammatik', frage: 'Wie lautet der Konjunktiv I von „er hat"?', antworten: ['er hätte', 'er hatte', 'er habe', 'er häbe'], richtig: 2, erklaerung: 'Der Konjunktiv I steht vor allem in der indirekten Rede: Er sagt, er habe Hunger. „hätte" ist der Konjunktiv II.', schwere: 5 },
  { kategorie: 'Grammatik', frage: 'In welcher Zeitform steht der Satz „Er wird angekommen sein."?', antworten: ['Futur I', 'Perfekt', 'Plusquamperfekt', 'Futur II'], richtig: 3, erklaerung: 'Eine Form von „werden" plus Partizip II plus „sein" oder „haben" ergibt das Futur II, die vollendete Zukunft.', schwere: 5 },
  { kategorie: 'Grammatik', frage: 'Welches Satzglied ist „der Opfer" im Satz „Wir gedenken der Opfer."?', antworten: ['Genitivobjekt', 'Dativobjekt', 'Akkusativobjekt', 'Subjekt'], richtig: 0, erklaerung: '„gedenken" verlangt den Genitiv: Wessen gedenken wir? — der Opfer. Verben mit Genitivobjekt sind im Deutschen selten.', schwere: 5 },
  { kategorie: 'Grammatik', frage: 'Wie lautet die Mehrzahl von „Strauß", wenn der Vogel gemeint ist?', antworten: ['Sträuße', 'Strauße', 'Sträußer', 'Straußer'], richtig: 1, erklaerung: 'Der Blumenstrauß hat die Mehrzahl „Sträuße", der Vogel Strauß dagegen „Strauße" — ohne Umlaut.', schwere: 5 },
  { kategorie: 'Grammatik', frage: 'Wie lautet die Mehrzahl von „Mutter", wenn die Schraubenmutter gemeint ist?', antworten: ['Mütter', 'Mutters', 'Muttern', 'Mutteren'], richtig: 2, erklaerung: 'Die Mutter als Mensch hat die Mehrzahl „Mütter", die Schraubenmutter dagegen „Muttern".', schwere: 5 },
];
