import type { LeiterFrage } from '../../core/leiter';

/**
 * Wortschatz-Fragen für die Gewinnleiter — reine Daten, keine Logik.
 *
 * Vier Arten: Gegenteil, Synonym, Bedeutung (auch Fremdwörter) und Wortbildung (Wortfamilien,
 * Vor- und Nachsilben, zusammengesetzte Wörter). Je Schwere zehn Fragen.
 *
 * Bei Gegenteil und Synonym ist die größte Gefahr eine zweite vertretbare Lösung. Die drei falschen
 * Antworten sind deshalb so gewählt, dass keine davon als Gegen- bzw. Ersatzwort durchgehen kann —
 * wer hier eine Antwort austauscht, prüft genau das noch einmal.
 */
export const WORTFRAGEN_WORTSCHATZ: readonly LeiterFrage[] = [
  // ── Schwere 1: jedes Grundschulkind ─────────────────────────────────────────
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „heiß“?',
    antworten: ['kalt', 'nass', 'hell', 'weich'],
    richtig: 0,
    erklaerung: 'Heißer Tee dampft, ein Eiswürfel ist kalt — „heiß“ und „kalt“ sind ein Gegensatzpaar.',
    schwere: 1,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „Tag“?',
    antworten: ['Woche', 'Morgen', 'Nacht', 'Sonne'],
    richtig: 2,
    erklaerung: 'Am Tag ist es hell, in der Nacht ist es dunkel. Deshalb gehören „Tag“ und „Nacht“ als Gegensatz zusammen.',
    schwere: 1,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „voll“?',
    antworten: ['rund', 'leer', 'schwer', 'dick'],
    richtig: 1,
    erklaerung: 'Ein volles Glas kann man austrinken — danach ist es leer.',
    schwere: 1,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „laut“?',
    antworten: ['langsam', 'dunkel', 'weich', 'leise'],
    richtig: 3,
    erklaerung: 'Was laut ist, hört man gut. Was leise ist, hört man kaum — so wie ein Mäuschen.',
    schwere: 1,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet fast dasselbe wie „beginnen“?',
    antworten: ['anfangen', 'aufhören', 'warten', 'gewinnen'],
    richtig: 0,
    erklaerung: '„Der Film beginnt“ und „Der Film fängt an“ sagen dasselbe. „Aufhören“ ist das Gegenteil.',
    schwere: 1,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet fast dasselbe wie „sprechen“?',
    antworten: ['hören', 'reden', 'lesen', 'schweigen'],
    richtig: 1,
    erklaerung: 'Wer spricht oder redet, sagt etwas mit Worten. Schweigen ist das Gegenteil davon.',
    schwere: 1,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was ist eine „Pfütze“?',
    antworten: ['eine kleine Mütze', 'ein kleiner Singvogel', 'eine Wasserstelle am Boden', 'ein grünes Gemüse'],
    richtig: 2,
    erklaerung: 'Nach dem Regen sammelt sich Wasser in kleinen Mulden auf Wegen und Straßen. Mit Gummistiefeln kann man hineinspringen.',
    schwere: 1,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was macht jemand, der „flüstert“?',
    antworten: ['laut rufen', 'schnell laufen', 'fröhlich singen', 'ganz leise sprechen'],
    richtig: 3,
    erklaerung: 'Beim Flüstern spricht man so leise, dass nur jemand ganz in der Nähe es hört — zum Beispiel bei einem Geheimnis.',
    schwere: 1,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Aus welchen zwei Wörtern besteht „Haustür“?',
    antworten: ['Haus + Tür', 'Hau + Stür', 'Hase + Tür', 'Haus + Uhr'],
    richtig: 0,
    erklaerung: '„Haustür“ ist zusammengesetzt: die Tür eines Hauses. Das letzte Wort sagt, was es ist — eine Tür.',
    schwere: 1,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Welches Wort gehört NICHT zur Wortfamilie von „spielen“?',
    antworten: ['Spieler', 'Spielzeug', 'Spiegel', 'verspielt'],
    richtig: 2,
    erklaerung: 'In Spieler, Spielzeug und verspielt steckt der Wortstamm „spiel“. „Spiegel“ sieht nur ähnlich aus und bedeutet etwas ganz anderes.',
    schwere: 1,
  },

  // ── Schwere 2: Klasse 5/6 ───────────────────────────────────────────────────
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet fast dasselbe wie „riesig“?',
    antworten: ['winzig', 'gewaltig', 'eckig', 'ruhig'],
    richtig: 1,
    erklaerung: 'Etwas Riesiges ist sehr groß, genau wie etwas Gewaltiges. „Winzig“ ist das Gegenteil.',
    schwere: 2,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet fast dasselbe wie „Angst“?',
    antworten: ['Mut', 'Wut', 'Neid', 'Furcht'],
    richtig: 3,
    erklaerung: 'Angst und Furcht meinen dasselbe Gefühl: Man fühlt sich bedroht. Mut ist das Gegenteil.',
    schwere: 2,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welcher Ausdruck bedeutet dasselbe wie „sich irren“?',
    antworten: ['sich ärgern', 'sich täuschen', 'sich beeilen', 'sich wundern'],
    richtig: 1,
    erklaerung: 'Wer sich irrt, hält etwas Falsches für richtig: „Ich dachte, heute ist Montag — da habe ich mich getäuscht.“',
    schwere: 2,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „ehrlich“?',
    antworten: ['höflich', 'fleißig', 'verlogen', 'neugierig'],
    richtig: 2,
    erklaerung: 'Wer ehrlich ist, sagt die Wahrheit. Wer verlogen ist, lügt immer wieder.',
    schwere: 2,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „Lob“?',
    antworten: ['Tadel', 'Preis', 'Dank', 'Ruhm'],
    richtig: 0,
    erklaerung: 'Ein Lob bekommt man für etwas, das gut gelungen ist, einen Tadel für etwas, das man falsch gemacht hat.',
    schwere: 2,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „Vorteil“?',
    antworten: ['Anteil', 'Urteil', 'Bestandteil', 'Nachteil'],
    richtig: 3,
    erklaerung: 'Ein Vorteil hilft einem, ein Nachteil macht es schwerer. Beim Basketball ist es ein Vorteil, groß zu sein.',
    schwere: 2,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was bedeutet „ratlos“?',
    antworten: ['ohne Geld in der Tasche', 'sehr müde', 'nicht weiterwissen', 'schlecht gelaunt'],
    richtig: 2,
    erklaerung: '„Ratlos“ heißt: ohne Rat. Man weiß nicht weiter und hat keine Idee, was man jetzt tun soll.',
    schwere: 2,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was ist eine „Ausrede“?',
    antworten: ['ein vorgeschobener Grund', 'ein langer Vortrag', 'ein Schimpfwort', 'ein Gespräch im Freien'],
    richtig: 0,
    erklaerung: 'Mit einer Ausrede erfindet man einen Grund, um sich herauszureden — etwa: „Der Hund hat mein Heft gefressen.“',
    schwere: 2,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Welches Wort gehört NICHT zur Wortfamilie von „fahren“?',
    antworten: ['Fahrer', 'Farbe', 'Fähre', 'Fahrkarte'],
    richtig: 1,
    erklaerung: 'Fahrer, Fähre und Fahrkarte haben alle mit dem Fahren zu tun. „Farbe“ klingt nur ähnlich.',
    schwere: 2,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Mit welcher Vorsilbe wird „glücklich“ zu seinem Gegenteil?',
    antworten: ['ver-', 'ent-', 'miss-', 'un-'],
    richtig: 3,
    erklaerung: 'Die Vorsilbe „un-“ dreht die Bedeutung um: glücklich – unglücklich, freundlich – unfreundlich.',
    schwere: 2,
  },

  // ── Schwere 3: Klasse 7 bis 9 ───────────────────────────────────────────────
  {
    kategorie: 'Bedeutung',
    frage: 'Was bedeutet „kontrovers“?',
    antworten: ['langweilig', 'umstritten', 'sehr genau', 'unbekannt'],
    richtig: 1,
    erklaerung: 'Über ein kontroverses Thema wird heftig gestritten, weil die Meinungen weit auseinandergehen.',
    schwere: 3,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was bedeutet „naiv“?',
    antworten: ['frech', 'ängstlich', 'sehr klug', 'leichtgläubig'],
    richtig: 3,
    erklaerung: 'Wer naiv ist, glaubt anderen schnell alles und durchschaut keine Tricks — oft, weil ihm noch die Erfahrung fehlt.',
    schwere: 3,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was ist ein „Kompromiss“?',
    antworten: ['eine Einigung durch Nachgeben', 'ein heftiger Streit', 'ein feierliches Versprechen', 'eine gute Ausrede'],
    richtig: 0,
    erklaerung: 'Bei einem Kompromiss bekommt keiner ganz, was er wollte: Beide geben etwas nach und treffen sich in der Mitte.',
    schwere: 3,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was ist ein „Fazit“?',
    antworten: ['eine Einleitung', 'eine Vermutung', 'eine Schlussfolgerung', 'ein Einwand'],
    richtig: 2,
    erklaerung: 'Das Fazit steht am Ende und fasst zusammen, was sich ergeben hat: „Mein Fazit: Der Ausflug hat sich gelohnt.“',
    schwere: 3,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet dasselbe wie „eventuell“?',
    antworten: ['vielleicht', 'schließlich', 'sicher', 'sofort'],
    richtig: 0,
    erklaerung: '„Eventuell“ heißt „vielleicht, unter Umständen“. Vorsicht: Das englische „eventually“ bedeutet „schließlich“ — ein typischer falscher Freund.',
    schwere: 3,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet dasselbe wie „Prognose“?',
    antworten: ['Rückblick', 'Vorhersage', 'Untersuchung', 'Behandlung'],
    richtig: 1,
    erklaerung: 'Eine Prognose sagt voraus, wie sich etwas entwickeln wird — etwa das Wetter oder der Verlauf einer Krankheit.',
    schwere: 3,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „sparsam“?',
    antworten: ['geizig', 'arm', 'verschwenderisch', 'gierig'],
    richtig: 2,
    erklaerung: 'Wer sparsam ist, gibt wenig aus, wer verschwenderisch ist, sehr viel. „Geizig“ ist kein Gegenteil, sondern übertrieben sparsam.',
    schwere: 3,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „optimistisch“?',
    antworten: ['realistisch', 'egoistisch', 'fantastisch', 'pessimistisch'],
    richtig: 3,
    erklaerung: 'Optimisten erwarten, dass etwas gut ausgeht, Pessimisten rechnen mit dem Schlimmsten. Lateinisch heißt „optimus“ der Beste, „pessimus“ der Schlechteste.',
    schwere: 3,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Welches Wort gehört NICHT zur Wortfamilie von „hören“?',
    antworten: ['Gehör', 'Horn', 'gehorsam', 'Zuhörer'],
    richtig: 1,
    erklaerung: 'Gehör, Zuhörer und sogar „gehorsam“ (auf jemanden hören) stammen von „hören“. Das Horn hat damit nichts zu tun.',
    schwere: 3,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Was ist das „s“ in „Arbeitszimmer“?',
    antworten: ['ein Fugenlaut', 'ein Mehrzahl-s', 'ein Genitiv-s', 'ein Tippfehler'],
    richtig: 0,
    erklaerung: 'Das „s“ verbindet „Arbeit“ und „Zimmer“ und heißt Fugenlaut oder Fugen-s. Ein Genitiv kann es nicht sein: Es heißt „der Arbeit“, ohne s.',
    schwere: 3,
  },

  // ── Schwere 4: Allgemeinbildung eines Erwachsenen ───────────────────────────
  {
    kategorie: 'Bedeutung',
    frage: 'Was bedeutet „paradox“?',
    antworten: ['altmodisch', 'vorbildlich', 'widersprüchlich', 'übertrieben'],
    richtig: 2,
    erklaerung: 'Paradox ist, was sich selbst zu widersprechen scheint. Beispiel: „Je mehr man wegnimmt, desto größer wird es.“ — ein Loch.',
    schwere: 4,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was bedeutet „obsolet“?',
    antworten: ['veraltet', 'zwingend nötig', 'fehlerhaft', 'verdächtig'],
    richtig: 0,
    erklaerung: 'Was obsolet ist, wird nicht mehr gebraucht, weil es überholt ist — so wie ein Faxgerät in vielen Büros.',
    schwere: 4,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Wie heißt ein Wort mit gegenteiliger Bedeutung, etwa „kalt“ zu „heiß“?',
    antworten: ['Synonym', 'Homonym', 'Pseudonym', 'Antonym'],
    richtig: 3,
    erklaerung: 'Ein Antonym ist ein Gegenwort (heiß – kalt), ein Synonym ein Wort mit gleicher Bedeutung (riesig – gewaltig). Griechisch „anti“ heißt „gegen“.',
    schwere: 4,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet dasselbe wie „ambivalent“?',
    antworten: ['beidhändig', 'zwiespältig', 'zweisprachig', 'gleichgültig'],
    richtig: 1,
    erklaerung: 'Ambivalente Gefühle sind zwiespältig: Man freut sich und ist zugleich traurig — etwa beim Umzug in eine neue Stadt.',
    schwere: 4,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welcher Ausdruck bedeutet dasselbe wie „akribisch“?',
    antworten: ['peinlich genau', 'scharfzüngig', 'überheblich', 'nachlässig'],
    richtig: 0,
    erklaerung: 'Wer akribisch arbeitet, achtet auf jede Kleinigkeit. Das Wort geht auf das griechische „akribés“ (genau, sorgfältig) zurück.',
    schwere: 4,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet dasselbe wie „Usus“?',
    antworten: ['Ausnahme', 'Brauch', 'Unsinn', 'Vorschrift'],
    richtig: 1,
    erklaerung: '„Das ist hier so Usus“ heißt: Das macht man hier so, es ist üblich. Das Wort kommt vom lateinischen „usus“ (Gebrauch).',
    schwere: 4,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „Prolog“?',
    antworten: ['Dialog', 'Monolog', 'Epilog', 'Katalog'],
    richtig: 2,
    erklaerung: 'Ein Prolog ist ein Vorwort oder Vorspiel vor der Handlung, ein Epilog das Nachwort oder Nachspiel am Ende.',
    schwere: 4,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil von „konvex“?',
    antworten: ['konform', 'konstant', 'kompakt', 'konkav'],
    richtig: 3,
    erklaerung: 'Konvex heißt nach außen gewölbt wie ein Hügel, konkav nach innen gewölbt wie eine Schüssel. In „konkav“ steckt lateinisch „cavus“ (hohl).',
    schwere: 4,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Welches Wort gehört NICHT zur Wortfamilie von „sehen“?',
    antworten: ['Aussicht', 'Sehnsucht', 'Fernseher', 'Sehenswürdigkeit'],
    richtig: 1,
    erklaerung: 'Aussicht, Fernseher und Sehenswürdigkeit stammen von „sehen“. „Sehnsucht“ kommt dagegen von „sich sehnen“ — mit dem Sehen hat es nichts zu tun.',
    schwere: 4,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Was bedeutet die Vorsilbe „poly-“ wie in „Polygon“?',
    antworten: ['halb', 'gleich', 'viel', 'eins'],
    richtig: 2,
    erklaerung: '„Poly-“ kommt aus dem Griechischen und heißt „viel“: Ein Polygon ist ein Vieleck, und wer polyglott ist, spricht viele Sprachen.',
    schwere: 4,
  },

  // ── Schwere 5: knifflig ─────────────────────────────────────────────────────
  {
    kategorie: 'Bedeutung',
    frage: 'Was bedeutet „lapidar“?',
    antworten: ['kurz und knapp', 'weitschweifig', 'feierlich', 'empört'],
    richtig: 0,
    erklaerung: 'Eine lapidare Antwort ist kurz und bündig, ohne große Worte — etwa nur „Nein.“ auf eine lange Frage.',
    schwere: 5,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was bedeutet „sukzessive“?',
    antworten: ['erfolgreich', 'plötzlich', 'nach und nach', 'gleichzeitig'],
    richtig: 2,
    erklaerung: 'Sukzessive heißt schrittweise, allmählich: „Die Straße wird sukzessive erneuert.“ Es bedeutet nicht „erfolgreich“, auch wenn es an das englische „successful“ erinnert.',
    schwere: 5,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was ist eine „Petitesse“?',
    antworten: ['eine Bittschrift', 'eine Kleinigkeit', 'ein kleines Gebäck', 'eine Schmeichelei'],
    richtig: 1,
    erklaerung: 'Eine Petitesse ist eine unwichtige Kleinigkeit, über die man nicht lange reden muss. Das Wort kommt vom französischen „petit“ (klein).',
    schwere: 5,
  },
  {
    kategorie: 'Bedeutung',
    frage: 'Was bedeutet „ubiquitär“?',
    antworten: ['sehr selten', 'uralt', 'unsichtbar', 'überall verbreitet'],
    richtig: 3,
    erklaerung: 'Ubiquitär heißt überall vorkommend — Smartphones sind heute zum Beispiel ubiquitär. Das lateinische „ubique“ bedeutet „überall“.',
    schwere: 5,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet dasselbe wie „eloquent“?',
    antworten: ['redegewandt', 'gut gekleidet', 'eingebildet', 'schweigsam'],
    richtig: 0,
    erklaerung: 'Wer eloquent ist, kann sich gewandt und überzeugend ausdrücken. Das Wort geht auf das lateinische „eloqui“ (aussprechen) zurück.',
    schwere: 5,
  },
  {
    kategorie: 'Synonym',
    frage: 'Welches Wort bedeutet dasselbe wie „konziliant“?',
    antworten: ['kirchlich', 'entgegenkommend', 'widerspenstig', 'kurz gefasst'],
    richtig: 1,
    erklaerung: 'Ein konzilianter Mensch ist umgänglich und kommt anderen entgegen, zum Beispiel in einer schwierigen Verhandlung.',
    schwere: 5,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist in der Astronomie das Gegenteil des „Zenits“?',
    antworten: ['Horizont', 'Meridian', 'Nadir', 'Äquator'],
    richtig: 2,
    erklaerung: 'Der Zenit ist der Punkt genau senkrecht über dem Beobachter, der Nadir der Punkt genau senkrecht unter ihm. „Nadir“ kommt aus dem Arabischen.',
    schwere: 5,
  },
  {
    kategorie: 'Gegenteil',
    frage: 'Was ist das Gegenteil eines „Misanthropen“?',
    antworten: ['Philanthrop', 'Philosoph', 'Anthropologe', 'Pessimist'],
    richtig: 0,
    erklaerung: 'Ein Misanthrop ist ein Menschenfeind, ein Philanthrop ein Menschenfreund. Griechisch „anthropos“ heißt Mensch, „misein“ hassen, „philein“ lieben.',
    schwere: 5,
  },
  {
    kategorie: 'Wortbildung',
    frage: 'Welches dieser Wörter gehört zur Wortfamilie von „tragen“?',
    antworten: ['Treppe', 'Trost', 'Traum', 'Getreide'],
    richtig: 3,
    erklaerung: '„Getreide“ hieß im Mittelhochdeutschen „getregede“: das, was getragen wird — also der Ertrag, den das Feld trägt.',
    schwere: 5,
  },
];
