import type { LeiterFrage } from '../../core/leiter';

/**
 * Redensarten, Sprichwörter, Oberbegriffe und gesicherte Herkunft von Redewendungen — je zehn Fragen
 * für die Schweren 1 bis 5. Herkunftsfragen stehen nur dort, wo die Herkunft unstrittig ist
 * (Sport, Eisenbahn, Bibel, Antike, alte Wortbedeutungen); Volksetymologien bleiben bewusst draußen.
 */
export const WORTFRAGEN_REDENSARTEN: readonly LeiterFrage[] = [
  // ── Schwere 1 ──────────────────────────────────────────────────────────────
  {
    kategorie: 'Sprichwort',
    frage: 'Wie geht das Sprichwort weiter: „Übung macht den …"?',
    antworten: ['Meister', 'Sieger', 'Lehrer', 'Fehler'],
    richtig: 0,
    erklaerung: 'Wer etwas oft übt, wird darin immer besser – irgendwann sogar richtig gut. Darum lohnt sich das Üben.',
    schwere: 1,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Ergänze das Sprichwort: „Lügen haben kurze …"',
    antworten: ['Arme', 'Beine', 'Haare', 'Ohren'],
    richtig: 1,
    erklaerung: 'Mit kurzen Beinen kommt man nicht weit – genauso fliegen Lügen meistens schnell auf.',
    schwere: 1,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Was fehlt im Sprichwort: „Morgenstund hat … im Mund"?',
    antworten: ['Brot', 'Honig', 'Gold', 'Zahnpasta'],
    richtig: 2,
    erklaerung: 'Gemeint ist: Wer früh aufsteht, schafft viel. Die frühen Morgenstunden sind besonders wertvoll.',
    schwere: 1,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet es, wenn du jemandem „die Daumen drückst"?',
    antworten: ['Du willst ihn ärgern', 'Du begrüßt ihn', 'Du tust ihm weh', 'Du wünschst ihm Glück'],
    richtig: 3,
    erklaerung: 'Wer jemandem die Daumen drückt, hofft mit ihm, dass etwas gut ausgeht – zum Beispiel vor einer Klassenarbeit.',
    schwere: 1,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was meint man mit: „Du hast wohl Tomaten auf den Augen!"?',
    antworten: ['Du übersiehst etwas Offensichtliches', 'Du hast rote Augen', 'Du hast großen Hunger', 'Du kochst sehr gut'],
    richtig: 0,
    erklaerung: 'Man sagt das zu jemandem, der etwas nicht bemerkt, das direkt vor seiner Nase liegt.',
    schwere: 1,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Jemand sagt: „Ich verstehe nur Bahnhof." Was meint er damit?',
    antworten: ['Er will verreisen', 'Er versteht gar nichts', 'Er hört einen Zug', 'Er wartet auf jemanden'],
    richtig: 1,
    erklaerung: '„Nur Bahnhof verstehen" heißt, dass man von dem Gesagten überhaupt nichts begreift.',
    schwere: 1,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet es, „Schmetterlinge im Bauch" zu haben?',
    antworten: ['Bauchweh haben', 'Sehr kitzlig sein', 'Verliebt sein', 'Großen Hunger haben'],
    richtig: 2,
    erklaerung: 'Wer frisch verliebt ist, spürt oft ein aufgeregtes Kribbeln im Bauch – so, als würden dort Schmetterlinge flattern.',
    schwere: 1,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welches Wort ist der Oberbegriff zu Hammer, Säge und Zange?',
    antworten: ['Spielzeug', 'Geschirr', 'Möbel', 'Werkzeug'],
    richtig: 3,
    erklaerung: 'Hammer, Säge und Zange sind Werkzeuge. Ein Oberbegriff fasst mehrere Dinge zusammen, die zu einer Gruppe gehören.',
    schwere: 1,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welches dieser Wörter passt nicht zu den anderen?',
    antworten: ['Tulpe', 'Hund', 'Katze', 'Pferd'],
    richtig: 0,
    erklaerung: 'Hund, Katze und Pferd sind Tiere. Die Tulpe ist eine Blume und passt deshalb nicht in die Reihe.',
    schwere: 1,
  },
  {
    kategorie: 'Herkunft',
    frage: 'Aus welchem Bereich stammt der Ausdruck „ein Eigentor schießen"?',
    antworten: ['Aus der Küche', 'Aus dem Sport', 'Aus der Schule', 'Aus der Seefahrt'],
    richtig: 1,
    erklaerung: 'Im Fußball ist ein Eigentor ein Treffer ins eigene Tor. Im Alltag heißt es: Man schadet sich mit einer Handlung selbst.',
    schwere: 1,
  },

  // ── Schwere 2 ──────────────────────────────────────────────────────────────
  {
    kategorie: 'Redewendung',
    frage: 'Was tut jemand, der dir „einen Bären aufbindet"?',
    antworten: ['Er schenkt dir etwas', 'Er gibt dir schwere Arbeit', 'Er schwindelt dich an', 'Er erschreckt dich'],
    richtig: 2,
    erklaerung: 'Wer einem anderen einen Bären aufbindet, erzählt ihm eine erfundene Geschichte und will, dass er sie glaubt.',
    schwere: 2,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet „ins Fettnäpfchen treten"?',
    antworten: ['Zu viel essen', 'Beim Kochen helfen', 'Schmutzige Schuhe haben', 'Etwas Unpassendes sagen'],
    richtig: 3,
    erklaerung: 'Wer ins Fettnäpfchen tritt, sagt oder tut aus Versehen etwas, das andere kränkt oder die Stimmung verdirbt.',
    schwere: 2,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was ist eine „Eselsbrücke"?',
    antworten: ['Eine Merkhilfe', 'Ein schmaler Steg', 'Eine Abkürzung', 'Ein dummer Fehler'],
    richtig: 0,
    erklaerung: 'Eine Eselsbrücke hilft beim Merken, zum Beispiel „Nie ohne Seife waschen" für die Himmelsrichtungen Nord, Ost, Süd, West.',
    schwere: 2,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet es, „auf dem Holzweg" zu sein?',
    antworten: ['Im Wald spazieren', 'Sich irren', 'Schnell vorankommen', 'Holz sammeln'],
    richtig: 1,
    erklaerung: 'Ein Holzweg diente früher nur zum Abtransport von Holz und endete mitten im Wald. Wer darauf ist, liegt mit seiner Meinung falsch.',
    schwere: 2,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Ergänze das Sprichwort: „Reden ist Silber, Schweigen ist …"',
    antworten: ['Bronze', 'Eisen', 'Gold', 'Kupfer'],
    richtig: 2,
    erklaerung: 'Manchmal ist es klüger, nichts zu sagen, als zu viel zu reden. Schweigen ist darum noch wertvoller als Silber.',
    schwere: 2,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Wie endet das Sprichwort: „Viele Köche verderben …"?',
    antworten: ['den Appetit', 'die Küche', 'das Fest', 'den Brei'],
    richtig: 3,
    erklaerung: 'Wenn zu viele Leute bei einer Sache mitreden, wird das Ergebnis oft schlechter statt besser.',
    schwere: 2,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Wie geht es weiter: „Wie man in den Wald hineinruft, …"?',
    antworten: ['so schallt es heraus', 'so kommen die Tiere', 'so wachsen die Bäume', 'so verirrt man sich'],
    richtig: 0,
    erklaerung: 'Wer andere freundlich behandelt, wird meist auch freundlich behandelt – und wer unfreundlich ist, bekommt Unfreundlichkeit zurück.',
    schwere: 2,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welches Tier passt nicht in die Reihe?',
    antworten: ['Adler', 'Fledermaus', 'Spatz', 'Amsel'],
    richtig: 1,
    erklaerung: 'Adler, Spatz und Amsel sind Vögel. Die Fledermaus kann zwar fliegen, ist aber ein Säugetier.',
    schwere: 2,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welcher Oberbegriff passt zu Kupfer, Eisen und Silber?',
    antworten: ['Edelsteine', 'Kunststoffe', 'Metalle', 'Brennstoffe'],
    richtig: 2,
    erklaerung: 'Kupfer, Eisen und Silber sind Metalle: Sie glänzen, leiten Strom und Wärme und lassen sich formen.',
    schwere: 2,
  },
  {
    kategorie: 'Herkunft',
    frage: 'Woher stammt die Redewendung „die Weichen stellen"?',
    antworten: ['Von der Seefahrt', 'Vom Gartenbau', 'Vom Bäcker', 'Von der Eisenbahn'],
    richtig: 3,
    erklaerung: 'Mit einer Weiche wird festgelegt, auf welches Gleis ein Zug fährt. Wer die Weichen stellt, legt die Richtung für die Zukunft fest.',
    schwere: 2,
  },

  // ── Schwere 3 ──────────────────────────────────────────────────────────────
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet es, in einer neuen Gruppe „das Eis zu brechen"?',
    antworten: ['Die anfängliche Scheu überwinden', 'Einen Streit anfangen', 'Ein Versprechen brechen', 'Etwas Kaltes trinken'],
    richtig: 0,
    erklaerung: 'Wer das Eis bricht, sorgt dafür, dass die erste Fremdheit verschwindet und alle locker miteinander reden.',
    schwere: 3,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was meint man mit „Da liegt der Hund begraben"?',
    antworten: ['Hier ist es unheimlich', 'Das ist der Kern der Sache', 'Das ist längst vergessen', 'Hier liegt ein Schatz versteckt'],
    richtig: 1,
    erklaerung: 'Man sagt das, wenn man den eigentlichen Grund für ein Problem gefunden hat: „Ach, da liegt der Hund begraben!"',
    schwere: 3,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was tut jemand, der etwas „durch die Blume" sagt?',
    antworten: ['Er macht ein Kompliment', 'Er ruft es laut', 'Er deutet es nur an', 'Er schreibt es auf'],
    richtig: 2,
    erklaerung: 'Wer etwas durch die Blume sagt, spricht es nicht direkt aus, sondern verpackt es höflich – oft eine Kritik.',
    schwere: 3,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet „die Katze im Sack kaufen"?',
    antworten: ['Ein Haustier kaufen', 'Ein Geheimnis verraten', 'Zu viel bezahlen', 'Etwas ungeprüft kaufen'],
    richtig: 3,
    erklaerung: 'Wer die Katze im Sack kauft, nimmt etwas, ohne es vorher anzusehen. Nicht verwechseln mit „die Katze aus dem Sack lassen" – ein Geheimnis verraten.',
    schwere: 3,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Wie geht das Sprichwort weiter: „Was Hänschen nicht lernt, …"?',
    antworten: ['lernt Hans nimmermehr', 'lernt Gretchen sofort', 'braucht er auch nicht', 'vergisst er nie'],
    richtig: 0,
    erklaerung: 'Was man als Kind lernt, fällt einem leicht. Als Erwachsener tut man sich mit Neuem oft schwerer.',
    schwere: 3,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Was fehlt? „Steter Tropfen höhlt den …"',
    antworten: ['Eimer', 'Stein', 'Baum', 'Boden'],
    richtig: 1,
    erklaerung: 'Ein einzelner Tropfen bewirkt nichts, aber viele über lange Zeit höhlen sogar Stein aus. So bringt auch Ausdauer ans Ziel.',
    schwere: 3,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Ergänze das Sprichwort: „Wer den Pfennig nicht ehrt, …"',
    antworten: ['bleibt für immer arm', 'wird niemals reich', 'ist des Talers nicht wert', 'verliert sein Geld'],
    richtig: 2,
    erklaerung: 'Wer kleine Beträge nicht schätzt, verdient auch große nicht. Der Taler war früher eine wertvolle Silbermünze.',
    schwere: 3,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welcher Oberbegriff passt zu Substantiv, Verb und Adjektiv?',
    antworten: ['Satzglieder', 'Zeitformen', 'Fälle', 'Wortarten'],
    richtig: 3,
    erklaerung: 'Substantiv (Namenwort), Verb (Tunwort) und Adjektiv (Wiewort) sind Wortarten. Satzglieder sind etwa Subjekt und Prädikat.',
    schwere: 3,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welches dieser Meerestiere ist kein Säugetier?',
    antworten: ['Hai', 'Wal', 'Delfin', 'Robbe'],
    richtig: 0,
    erklaerung: 'Wal, Delfin und Robbe sind Säugetiere und atmen mit Lungen. Der Hai ist ein Fisch und atmet mit Kiemen.',
    schwere: 3,
  },
  {
    kategorie: 'Herkunft',
    frage: 'Woher stammt der Ausdruck „Achillesferse" für eine verwundbare Stelle?',
    antworten: ['Aus der Bibel', 'Aus einer griechischen Sage', 'Aus einem Grimm-Märchen', 'Aus dem Fußball'],
    richtig: 1,
    erklaerung: 'Der griechische Held Achilles war fast unverwundbar – nur nicht an der Ferse. Genau dort traf ihn ein Pfeil.',
    schwere: 3,
  },

  // ── Schwere 4 ──────────────────────────────────────────────────────────────
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet „die Spreu vom Weizen trennen"?',
    antworten: ['Getreide ernten', 'Einen Streit schlichten', 'Gutes von Schlechtem trennen', 'Brot backen'],
    richtig: 2,
    erklaerung: 'Spreu sind die wertlosen Hüllen der Getreidekörner. Wer die Spreu vom Weizen trennt, sortiert das Brauchbare vom Unbrauchbaren.',
    schwere: 4,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Wie ist jemand, der „mit allen Wassern gewaschen" ist?',
    antworten: ['Sehr sauber', 'Sehr ehrlich', 'Ein guter Schwimmer', 'Sehr gerissen'],
    richtig: 3,
    erklaerung: 'So nennt man jemanden, der durch viel Erfahrung schlau und durchtrieben ist und dem man so leicht nichts vormachen kann.',
    schwere: 4,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was tut jemand, der anderen „Sand in die Augen streut"?',
    antworten: ['Er täuscht sie', 'Er macht sie müde', 'Er beleidigt sie', 'Er lobt sie'],
    richtig: 0,
    erklaerung: 'Wer anderen Sand in die Augen streut, versucht sie zu täuschen, damit sie die Wahrheit nicht erkennen.',
    schwere: 4,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Wie endet das Sprichwort: „Man muss das Eisen schmieden, …"?',
    antworten: ['bevor es rostet', 'solange es heiß ist', 'wenn der Meister kommt', 'so oft man kann'],
    richtig: 1,
    erklaerung: 'Man soll eine günstige Gelegenheit sofort nutzen – so wie der Schmied das Eisen nur glühend formen kann.',
    schwere: 4,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Ergänze: „Der Krug geht so lange zum Brunnen, …"',
    antworten: ['bis er voll ist', 'bis es dunkel wird', 'bis er bricht', 'bis er leer ist'],
    richtig: 2,
    erklaerung: 'Wer immer wieder etwas Riskantes tut, scheitert irgendwann oder wird erwischt.',
    schwere: 4,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Wie geht es weiter: „Wo gehobelt wird, …"?',
    antworten: ['da wird gebaut', 'da gibt es Lärm', 'da riecht es nach Holz', 'da fallen Späne'],
    richtig: 3,
    erklaerung: 'Wo gearbeitet wird, passieren auch Fehler oder es entstehen kleine Schäden – das lässt sich nie ganz vermeiden.',
    schwere: 4,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welcher Begriff aus der Grammatik passt nicht in die Reihe?',
    antworten: ['Präteritum', 'Nominativ', 'Genitiv', 'Dativ'],
    richtig: 0,
    erklaerung: 'Nominativ, Genitiv und Dativ sind Fälle (Kasus). Das Präteritum ist eine Zeitform, die einfache Vergangenheit.',
    schwere: 4,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welcher Oberbegriff passt zu Metapher, Alliteration und Ironie?',
    antworten: ['Versmaße', 'Stilmittel', 'Satzglieder', 'Zeitformen'],
    richtig: 1,
    erklaerung: 'Metapher (bildhafter Ausdruck), Alliteration (gleicher Anlaut) und Ironie sind Stilmittel – sie verändern, wie ein Text wirkt.',
    schwere: 4,
  },
  {
    kategorie: 'Herkunft',
    frage: '„Das A und O" meint den ersten und letzten Buchstaben eines Alphabets. Welches?',
    antworten: ['Das lateinische', 'Das hebräische', 'Das griechische', 'Das kyrillische'],
    richtig: 2,
    erklaerung: 'Alpha und Omega sind der erste und letzte Buchstabe des griechischen Alphabets. In der Bibel heißt es: „Ich bin das A und das O." Heute meint es: das Wichtigste.',
    schwere: 4,
  },
  {
    kategorie: 'Herkunft',
    frage: '„Den Rubikon überschreiten" geht auf einen Feldherrn zurück. Wer zog 49 v. Chr. mit seinem Heer über diesen Fluss?',
    antworten: ['Hannibal', 'Alexander der Große', 'Kaiser Nero', 'Julius Caesar'],
    richtig: 3,
    erklaerung: 'Mit dem Überschreiten des Grenzflusses löste Caesar einen Bürgerkrieg aus – es gab kein Zurück mehr. Heute heißt es: eine endgültige Entscheidung treffen.',
    schwere: 4,
  },

  // ── Schwere 5 ──────────────────────────────────────────────────────────────
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet „sein Licht unter den Scheffel stellen"?',
    antworten: ['Seine Fähigkeiten verbergen', 'Sich wichtig machen', 'Strom sparen', 'Früh schlafen gehen'],
    richtig: 0,
    erklaerung: 'Ein Scheffel war ein Gefäß für Getreide. Wer sein Licht darunter stellt, ist zu bescheiden und zeigt nicht, was er kann. Das Bild stammt aus der Bibel.',
    schwere: 5,
  },
  {
    kategorie: 'Redewendung',
    frage: 'Was bedeutet die Redensart „jemanden über den Löffel barbieren"?',
    antworten: ['Jemanden füttern', 'Jemanden betrügen', 'Jemanden trösten', 'Jemanden loben'],
    richtig: 1,
    erklaerung: '„Barbieren" ist ein altes Wort für rasieren (auch „balbieren" gesagt). Gemeint ist: jemanden plump hereinlegen und übervorteilen.',
    schwere: 5,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Wie geht das alte Sprichwort weiter: „Wes Brot ich ess, …"?',
    antworten: ['dem dank ich sehr', 'des Haus ich bau', 'des Lied ich sing', 'den lob ich laut'],
    richtig: 2,
    erklaerung: 'Wer von jemandem bezahlt oder versorgt wird, vertritt oft auch dessen Meinung. „Wes" ist eine alte Form von „wessen".',
    schwere: 5,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Ergänze das Sprichwort: „Müßiggang ist aller …"',
    antworten: ['Freuden Quell', 'Weisheit Ende', 'Tage Ruhe', 'Laster Anfang'],
    richtig: 3,
    erklaerung: 'Müßiggang heißt Nichtstun. Das Sprichwort warnt: Wer nur faulenzt, kommt leicht auf dumme Gedanken.',
    schwere: 5,
  },
  {
    kategorie: 'Sprichwort',
    frage: 'Was fehlt im Sprichwort: „Viele Hunde sind des … Tod"?',
    antworten: ['Hasen', 'Fuchses', 'Jägers', 'Katers'],
    richtig: 0,
    erklaerung: 'Gegen eine große Übermacht kann auch der Schnellste nichts ausrichten – so wie ein Hase gegen eine ganze Hundemeute.',
    schwere: 5,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welcher Begriff passt nicht in die Reihe der anderen drei?',
    antworten: ['Jambus', 'Hyperbel', 'Trochäus', 'Daktylus'],
    richtig: 1,
    erklaerung: 'Jambus, Trochäus und Daktylus sind Versfüße, also Muster aus betonten und unbetonten Silben. Die Hyperbel ist ein Stilmittel: eine starke Übertreibung.',
    schwere: 5,
  },
  {
    kategorie: 'Oberbegriff',
    frage: 'Welches Wort aus der Musik passt nicht in die Reihe?',
    antworten: ['Allegro', 'Adagio', 'Sopran', 'Andante'],
    richtig: 2,
    erklaerung: 'Allegro (schnell), Adagio (langsam) und Andante (gehend) sind Tempoangaben. Sopran ist dagegen eine Stimmlage, die höchste Singstimme.',
    schwere: 5,
  },
  {
    kategorie: 'Herkunft',
    frage: 'Etwas „aus dem Stegreif" tun heißt: ohne Vorbereitung. Was war ein Stegreif ursprünglich?',
    antworten: ['Ein Notenständer', 'Ein Rednerpult', 'Ein Spazierstock', 'Ein Steigbügel'],
    richtig: 3,
    erklaerung: 'Der Stegreif war der Steigbügel am Sattel. Wer etwas aus dem Stegreif erledigte, tat es, ohne vom Pferd abzusteigen – also sofort.',
    schwere: 5,
  },
  {
    kategorie: 'Herkunft',
    frage: 'Worauf geht die Redensart „jemandem ein X für ein U vormachen" zurück?',
    antworten: ['Auf römische Zahlzeichen', 'Auf eine Geheimschrift', 'Auf ein Würfelspiel', 'Auf alte Musiknoten'],
    richtig: 0,
    erklaerung: 'Das römische V (früher auch als U geschrieben) bedeutet 5. Verlängert man seine Striche nach unten, entsteht ein X, also 10 – so ließ sich eine Zahl heimlich verdoppeln.',
    schwere: 5,
  },
  {
    kategorie: 'Herkunft',
    frage: 'Woher stammt die Redensart „jemandem auf den Leim gehen"?',
    antworten: ['Vom Tischlern', 'Vom Vogelfang', 'Vom Tapezieren', 'Vom Buchbinden'],
    richtig: 1,
    erklaerung: 'Früher fing man Vögel mit Leimruten, also mit klebrigem Leim bestrichenen Zweigen. Wer jemandem auf den Leim geht, fällt auf einen Trick herein.',
    schwere: 5,
  },
];
